[[fblangref-tablevalue-functions]]
= Табличные функции

Табличные функции -- это функции, возвращающие набор строк, которые состоят из одного или нескольких столбцов скалярных типов. Они применяются в запросах как таблицы, представления или подзапросы в предложении `FROM`. Столбцы, возвращённые табличными функциями, можно включить в выражения `SELECT`, `JOIN` или `WHERE` так же, как столбцы таблиц, представлений или подзапросов.

В общем виде вызов табличной функции выглядит следующим образом:

.Синтаксис
[listing,subs="+quotes, macros"]
----
<table value function> ::=
  _function_name_ (<args>) [AS] <correlation name> [(<derived column list>)]

<derived column list> ::=
  <derived column name> [, <derived column name> ... ]
----

[[fblangref-tablefuncs-tbl]]
.Параметры табличных функций
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|function_name
|Имя табличной функции.

|correlation name
|Псевдоним набора записей, возвращаемого табличной функцией. Это обязательный параметр (согласно стандарту SQL).

|derived column name
|Псевдоним столбца для набора записей, возвращаемого табличной функцией.

|===

[NOTE]
====
Табличные функции очень похожи на хранимые процедуры выбора, но в отличии от процедур в настоящее время пользователь не может создавать свои табличные функции. Таким образом табличную функцию можно рассматривать как встроенную хранимую процедуру выбора.
====

[[fblangref-tablefunc-unlist]]
== UNLIST

Функция `UNLIST` анализирует входную строку, используя указанный разделитель (по умолчанию подразумевается запятая ",") и возвращает подстроки как дискретные записи, содержащие одно поле. Кроме того, можно указать желаемый тип возвращаемого поля. Если указанное преобразование типа данных невозможно, во время выполнения возникает ошибка.

.Синтаксис
[listing,subs="+quotes, macros"]
----
UNLIST (<input> [, <separator>] [<data type conversion>]) [AS] <correlation name> [(<derived column name>)]

<input> ::= <value>

<separator> ::= <value>

<data type conversion> ::= RETURNING <data type>
----

.Параметры функции `UNLIST`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|input
|Любое выражение, которое возвращает строку символов или BLOB (или может быть преобразовано в строку). Этот параметр является обязательным.

|separator
|Необязательное выражение, которое возвращает строку, которая используется как разделитель (т. е. отделяет одно значение от другого внутри входной строки). Если указана пустая строка, то на выходе будет только одна запись, содержащая входную строку. Если этот параметр пропущен, в качестве разделителя используется запятая. Максимальная длинна разделителя ограничена 32 Кбайт.

|data type
|Целевой тип данных для преобразования выходных значений. В качестве альтернативы в качестве возвращаемого типа можно указать домен. Если этот параметр пропущен, подразумевается `VARCHAR(32)`. Старайтесь всегда указывать тип выходного результата, заменяя тип по умолчанию.

|correlation name
|Псевдоним набора записей, возвращаемого функцией `UNLIST`. Это обязательный параметр (согласно стандарту SQL).

|derived column name
|Необязательный псевдоним столбца, возвращаемого функцией `UNLIST`. Если этот параметр пропущен, то возвращаемый столбец имеет имя `UNLIST`.
|===

.Использование UNLIST в SQL запросах
[example]
====
[source,sql]
----
SELECT * FROM UNLIST('1,2,3,4,5') AS U;

SELECT * FROM UNLIST('100:200:300:400:500', ':' RETURNING INT) AS U;

SELECT U.* FROM UNLIST('text1, text2, text3') AS U;

SELECT C0 FROM UNLIST('text1, text2, text3') AS U(C0);

SELECT U.C0 FROM UNLIST('text1, text2, text3') AS U(C0);

SELECT
    COLOR.*
FROM
    UNLIST('1,2,3,4,5' RETURNING INT) AS U(I)
    JOIN COLOR ON COLOR.CODE_COLOR = U.I;
----
====

.Использование UNLIST в PSQL
[example]
====
[source,sql]
----
SET TERM ^ ;

RECREATE PROCEDURE TEST_PROC RETURNS (PROC_RETURN_INT INT)
AS
DECLARE VARIABLE text VARCHAR(11);
BEGIN
    text = '123:123:123';
    FOR
        SELECT * FROM UNLIST( :text, ':' RETURNING INT) AS A
        INTO :PROC_RETURN_INT
    DO
        SUSPEND;
END^

SET TERM ; ^

SELECT * FROM TEST_PROC;
----
====

.Преобразование результирующего столбца функции UNLIST к типу домену или типу столбца
[example]
====
[source,sql]
----
CREATE DOMAIN D1 AS INT;
SELECT TEST_DOMAIN FROM UNLIST('1,2,3,4' RETURNING D1) AS A(TEST_DOMAIN);

CREATE TABLE TABLE_TEST (COL1 INT);
SELECT TEST_TYPE_OF
FROM UNLIST('1,2,3,4' RETURNING TYPE OF COLUMN TABLE_TEST.COL1) AS A(TEST_TYPE_OF);
----
====

[IMPORTANT]
====
Непосредственное указание `UNLIST` в качестве столбца в предложении `SELECT` запрещено.

[source,sql]
----
SELECT UNLIST FROM UNLIST('1,2,3') AS A;
----

Данный запрос вызовет ошибку "столбец UNLIST не существует".

[source,sql]
----
SELECT * FROM UNLIST('1,2,3') AS A;
----

Однако этот запрос отработает без ошибок и в наборе данных имя возвращаемого столбца будет `UNLIST`.
====

[[fblangref-tablefunc-genseries]]
== GENERATE_SERIES

Функция `GENERATE_SERIES` создаёт ряд чисел в заданном интервале. Интервал и шаг между значениями рядов определяются пользователем.

.Синтаксис
[listing,subs="+quotes, macros"]
----
<generate_series_function> ::=
    GENERATE_SERIES(<start>, <finish> [, <step>]) [AS] <correlation name> [ ( <derived column name> ) ]
----

.Параметры функции `GENERATE_SERIES`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|start
|Начальное значение интервала. `start` может быть переменной, литералом или скалярным выражением типа `SMALLINT`, `INTEGER`, `BIGINT`, `INT128` или `NUMERIC/DECIMAL`.

|finish
|Конечное значение интервала. `finish` может быть переменной, литералом или скалярным выражением типа `SMALLINT`, `INTEGER`, `BIGINT`, `INT128` или `NUMERIC/DECIMAL`. Генерация последовательности останавливается, когда последнее сгенерированное значение шага превышает/принижает (зависит от знака `step`) значение `finish`.

|step
|Значение на которое изменяется результат между рядами на каждом шаге выполнения. `step` может быть выражением
типа `SMALLINT`, `INTEGER`, `BIGINT`, `INT128` или `NUMERIC/DECIMAL`. Значение `step` может быть как отрицательным, так и положительным, но не может быть равен нулю (0). Этот аргумент необязателен. По умолчанию значение `step` равно 1.

|===

Функция `GENERATE_SERIES` возвращает набор данных столбцом типа `BIGINT`, `INT128` или `NUMERIC(18, x)/NUMERIC(38, x)`, где масштаб определяется максимальным из масштабов аргументов функции.

Правила:

* Если `start > finish` и указано отрицательное значение `step`, возвращается пустой набор.
* Если `start < finish` и указано положительное значение `step`, возвращается пустой набор.
* Если аргумент `step` равен нулю, то возникает ошибка.

.Использование GENERATE_SERIES в SQL запросах
[example]
====
[source,sql]
----
SELECT n
FROM GENERATE_SERIES(1, 3) AS S(n);

SELECT n
FROM GENERATE_SERIES(3, 1, -1) AS S(n);

SELECT n
FROM GENERATE_SERIES(0, 9.9, 0.1) AS S(n);

SELECT
  DATEADD(n MINUTE TO timestamp '2025-01-01 12:00') AS START_TIME,
  DATEADD(n MINUTE TO timestamp '2025-01-01 12:00:59.9999') AS FINISH_TIME
FROM GENERATE_SERIES(0, 59) AS S(n);
----
====

[IMPORTANT]
====
Непосредственное указание `GENERATE_SERIES` в качестве столбца в предложении `SELECT` запрещено.

[source,sql]
----
SELECT GENERATE_SERIES FROM GENERATE_SERIES(1, 3) AS S;
----

Данный запрос вызовет ошибку "столбец GENERATE_SERIES не существует".

[source,sql]
----
SELECT GENERATE_SERIES FROM GENERATE_SERIES(1, 3) AS S;
----

Однако этот запрос отработает без ошибок и в наборе данных имя возвращаемого столбца будет `GENERATE_SERIES`.
====
