[[fblangref-security-granting]]
= Операторы для предоставления привилегий и назначения ролей

Оператор `GRANT` используется для предоставления привилегий и назначения ролей, пользователям и другим объектам базы данных.

[[fblangref-security-grant]]
== `GRANT`

.Назначение
Предоставление привилегий или назначение ролей.
(((GRANT)))

.Доступно в
DSQL

[[fblangref-security-grant-privsyntax]]
.Синтаксис (предоставление привилегий)
[listing,subs=+quotes]
----
GRANT <privileges>
  TO <grantee_list>
  [WITH GRANT OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<privileges> ::=
    <table_privileges> | <execute_privilege>
  | <usage_privilege>  | <ddl_privileges>
  | <db_ddl_privilege>

<table_privileges> ::=
  {ALL [PRIVILEGES] | <table_privilege_list> }
    ON [TABLE] [_schema_name_.]{_table_name_ | _view_name_}

<table_privilege_list> ::=
  <table_privilege> [, <tableprivilege> ...]

<table_privilege> ::=
    SELECT | DELETE | INSERT
  | UPDATE [(_col_ [, _col_ ...])]
  | REFERENCES [(_col_ [, _col_ ...)]

<execute_privilege> ::= EXECUTE ON {
    PROCEDURE [_schema_name_.]_proc_name_
  | FUNCTION [_schema_name_.]_func_name_
  | PACKAGE [_schema_name_.]_package_name_ }

<usage_privilege> ::= USAGE ON {
    SCHEMA _schema_name_
  | EXCEPTION [_schema_name_.]_exception_name_
  | {GENERATOR | SEQUENCE} [_schema_name_.]_sequence_name_ }

<ddl_privileges> ::=
  {ALL [PRIVILEGES] | <ddl_privilege_list>}
  {[ON SCHEMA _schema_name_] <object_type> | <schemaless_object_type>}


<ddl_privilege_list> ::=
  <ddl_privilege> [, <ddl_privilege> ...]

<ddl_privilege> ::= CREATE | ALTER ANY | DROP ANY

<object_type> ::=
    CHARACTER SET | COLLATION | DOMAIN | EXCEPTION
  | FILTER | FUNCTION | GENERATOR | PACKAGE
  | PROCEDURE | ROLE | SEQUENCE | TABLE | VIEW

<schemaless_object_type> ::=
    FILTER | ROLE | SCHEMA

<db_ddl_privileges> ::=
  {ALL [PRIVILEGES] | <db_ddl_privilege_list>} DATABASE

<db_ddl_privilege_list> ::=
  <db_ddl_privilege> [, <db_ddl_privilege> ...]

<db_ddl_privilege> ::= CREATE | ALTER | DROP

<grantee_list> ::= <grantee> [, <grantee> ...]

<grantee> ::=
    PROCEDURE [_schema_name_.]_proc_name_
  | FUNCTION [_schema_name_.]_func_name_
  | PACKAGE [_schema_name_.]_package_name_
  | TRIGGER [_schema_name_.]_trig_name_
  | VIEW [_schema_name_.]_view_name_
  | ROLE _role_name_ | [USER] _username_
  | GROUP _Unix_group_ | PUBLIC
  | <sys_privileges>

<sys_privileges> ::= SYSTEM PRIVILEGE <sys_privileges_list>

<sys_privileges_list> ::= <sys_privilege> [, <sys_privilege> [, <sys_privilege> ...]]
----

[[fblangref-security-grant-rolesyntax]]
.Синтаксис (назначение ролей)
[listing,subs=+quotes]
----
GRANT <role_granted>
  TO <role_grantee_list>
  [WITH ADMIN OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<role_granted> ::= [DEFAULT] _role_name_ [, [DEFAULT] _role_name_ ...]

<role_grantee_list> ::=
  <role_grantee> [, <role_grantee> ...]

<role_grantee> ::=
    [USER] _username_
  | [ROLE] _grantee_role_name_
----


.Параметры оператора `GRANT`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|schema_name
|Имя схемы.

|table_name
|Имя таблицы, к которой должно быть предоставлена привилегия.

|view_name
|Имя представления, к которому должно быть предоставлена привилегия, или которому будут предоставлены привилегии.

|col
|Столбец таблицы, к которому должна быть применена привилегия.

|proc_name
|Имя хранимой процедуры, для которой должна быть выдана привилегия EXECUTE или которой будут предоставлены привилегии.

|func_name
|Имя хранимой функции (или UDF), для которой должна быть выдана привилегия EXECUTE или которой будут даны привилегии.

|package_name
|Имя пакета, для которого должна быть выдана привилегия EXECUTE или которому будут даны привилегии.

|exception_name
|Имя исключения, для которого должна быть выдана привилегия USAGE.

|generator_name
|Имя генератора (последовательности), для которого должна быть выдана привилегия USAGE.

|object_type
|Тип объекта метаданных, который находится в одной из схем базы данных.

|schemaless_object_type
|Тип объекта метаданных, который находится вне схемы базы данных.

|object_list
|Список объектов метаданных, которым будут даны привилегии.

|trig_name
|Имя триггера, которому будут даны привилегии.

|user_list
|Список пользователей/ролей, которым будут выданы привилегии.

|username
|Имя пользователя, для которого выдаются привилегии или которому назначается роль.

|rolename
|Имя роли.

|Unix_group
|Имя группы пользователей в операционных системах семейства UNIX.
Только в Firebird Embedded.

|Unix_user
|Имя пользователя в операционной системе семейства UNIX.
Только в Firebird Embedded.

|sys_privilege
|Системная привилегия.

|role_granted
|Список ролей, которые будут назначены.

|role_grantee_list
|Список пользователей, которым будут назначены роли.

|grantor
|Пользователь от имени, которого предоставляются привилегии.
|===

Оператор `GRANT` предоставляет одну или несколько привилегий для объектов базы данных: схемам, пользователям, ролям, хранимым процедурам, функциям, пакетам, триггерам и представлениям.

Авторизованный пользователь не имеет никаких привилегий до тех пор, пока какие-либо права не будут предоставлены ему явно. При создании объекта только его создатель, владелец схемы, в которой создан объект, и администраторы базы данных имеют привилегии на него и могут назначать привилегии другим пользователям, ролям или объектам.

Для различных типов объектов метаданных существует различный набор привилегий. Эти привилегии будут описаны далее отдельно для каждого из типов объектов метаданных.

[[fblangref-security-grant-to-clause]]
=== Предложение TO

В предложении `TO` указывается список пользователей, ролей и объектов базы данных (процедур, функций, пакетов, триггеров и представлений) для которых будут выданы перечисленные привилегии.

Необязательные предложения `USER` и `ROLE` позволяют уточнить, кому именно выдаётся привилегия. Если ключевое слово `USER` или `ROLE` не указано, то сервер проверяет, существует ли роль с данным именем, если таковой не существует, то привилегии назначаются пользователю.

Существование пользователя, которому выдаются права, не проверяются при выполнении оператора `GRANT`. Если привилегия выдаётся объекту базы данных, то необходимо обязательно указывать тип объекта.

.Рекомендация
[TIP]
====
Несмотря на то, что ключевые слова `USER` и `ROLE` не обязательные, желательно использовать их, чтобы избежать путаницы.
====

[[fblangref-security-grant-public]]
=== Пользователь `PUBLIC`

В SQL существует специальный пользователь `PUBLIC`, представляющий всех пользователей. Если какая-то операция разрешена пользователю `PUBLIC`, значит, любой аутентифицированный пользователь может выполнить эту операцию над указанным объектом.

[IMPORTANT]
====
Если привилегии назначены пользователю `PUBLIC`, то и отозваны они должны быть у пользователя `PUBLIC`.
====

[[fblangref-security-grant-grantoption]]
=== Предложение `WITH GRANT OPTION`

(((GRANT, WITH GRANT OPTION)))
Необязательное предложение `WITH GRANT OPTION` позволяет пользователям, указанным в списке пользователей, передавать другим пользователям привилегии указанные в списке привилегий.

[[fblangref-security-grant-grantedby]]
=== Предложение `GRANTED BY`

(((GRANT, GRANTED BY)))
При предоставлении прав в базе данных в качестве лица, предоставившего эти права, обычно записывается текущий пользователь. Используя предложение `GRANTED` BY можно предоставлять права от имени другого пользователя.
При использовании оператора `REVOKE` после `GRANTED BY` права будут удалены только в том случае, если они были зарегистрированы от удаляющего пользователя. Для облегчения миграции из некоторых других реляционных СУБД нестандартное предложение AS поддерживается как синоним оператора `GRANTED BY`.

Предложение `GRANTED BY` может использовать:

* Владелец базы данных;
* `SYSDBA`;
* Любой пользователь, имеющий права на роль `RDB$ADMIN` и указавший её при соединении с базой данных;
* При использовании флага `AUTO ADMIN MAPPING` -- любой администратор операционной системы Windows (при условии использования сервером доверенной авторизации -- trusted authentication), даже без указания роли.

Даже владелец роли не может использовать `GRANTED BY`, если он не находится в вышеупомянутом списке.

[[fblangref-security-grant-tablepriv]]
=== Табличные привилегии

Для таблиц и представлений в отличие от других объектов метаданных возможно использовании сразу нескольких привилегий.

[[fblangref-security-tbl-tableprivs]]
.Список привилегий для таблиц
`SELECT`::
Разрешает выборку данных (`SELECT`) из таблицы или представления.

`INSERT`::
Разрешает добавлять записи (`INSERT`) в таблицу или представление.

`UPDATE`::
Разрешает изменять записи (`UPDATE`) в таблице или представлении.
Можно указать ограничения, чтобы можно было изменять только указанные столбцы.

`DELETE`::
Разрешает удалять записи (`DELETE`) из таблицы или представления.

`REFERENCES`::
Разрешает ссылаться на указанные столбцы внешним ключом.
Необходимо указать для столбцов, на которых построен первичный ключ таблицы, если на неё есть ссылка внешним ключом другой таблицы.

`ALL`::
Объединяет привилегии `SELECT`, `INSERT`, `UPDATE`, `DELETE` и `REFERENCES`.

[[fblangref-security-grant-table-exmpl]]
==== Примеры `GRANT <privilege>` для таблиц

.Предоставление привилегий для таблиц
[example]
====
[source,sql]
----
-- Привилегии SELECT, INSERT на таблицу SALES из текущей схемы
-- пользователю ALEX
GRANT SELECT, INSERT ON TABLE SALES
TO USER ALEX;

-- Привилегия SELECT на таблицу CUSTOMER из схемы SHOP
-- ролям MANAGER, ENGINEER и пользователю IVAN
GRANT SELECT ON TABLE SHOP.CUSTOMER
TO ROLE MANAGER, ROLE ENGINEER, USER IVAN;

-- Все привилегии на таблицу CUSTOMER из схемы SHOP
-- для роли ADMINISTRATOR с возможностью передачи своих полномочий
GRANT ALL ON TABLE SHOP.CUSTOMER
TO ROLE ADMINISTRATOR WITH GRANT OPTION;

-- Привилегии SELECT и REFERENCE для столбца NAME таблицы COUNTRY
-- из схемы WAREHOUSE для всех пользователей
GRANT SELECT, REFERENCES (NAME) ON TABLE WAREHOUSE.COUNTRY
TO PUBLIC;

-- Выдача привилегии SELECT на таблицу EMPLOYEE из текущей схемы
-- для пользователя IVAN от имени пользователя ALEX
GRANT SELECT ON TABLE EMPLOYEE
TO USER IVAN GRANTED BY ALEX;

-- Выдача привилегии UPDATE для столбцов FIRST_NAME, LAST_NAME
-- таблицы EMPLOYEE схемы SHOP для пользователя IVAN
GRANT UPDATE (FIRST_NAME, LAST_NAME) ON TABLE SHOP.EMPLOYEE
TO USER IVAN;

-- Выдача привилегии INSERT на таблицу EMPLOYEE_PROJECT
-- для хранимой процедуры ADD_EMP_PROJ
-- таблица и хранимая процедура находятся в текущей схеме
GRANT INSERT ON EMPLOYEE_PROJECT
TO PROCEDURE ADD_EMP_PROJ;

-- Выдача привилегии INSERT на таблицу EMPLOYEE_PROJECT из схемы SHOP
-- для хранимой процедуры ADD_EMP_PROJ из схемы MANAGEMENT
GRANT INSERT ON SHOP.EMPLOYEE_PROJECT
TO PROCEDURE MANAGEMENT.ADD_EMP_PROJ;
----
====

[[fblangref-security-grant-execute]]
=== Привилегия `EXECUTE`

Привилегия `EXECUTE` (выполнение) применима к хранимым процедурам, хранимым функциям, пакетам и унаследованным внешним функциям (UDF), определяемых как `DECLARE EXTERNAL FUNCTION`.

Для хранимых процедур привилегия `EXECUTE` позволяет не только выполнять хранимые процедуры, но и делать выборку данных из селективных процедур (с помощью оператора `SELECT`).

[NOTE]
====
Привилегия может быть назначена только для всего пакета, а не для отдельных его подпрограмм.
====

[[fblangref-security-grant-execute-exmpl]]
==== Примеры предоставления привилегии `EXECUTE`

.Предоставление привилегии `EXECUTE`
[example]
====
[source,sql]
----
-- Выдача привилегии EXECUTE на хранимую процедуру ADD_EMP_PROJ
-- из текущей схемы для роли MANAGER
GRANT EXECUTE ON PROCEDURE ADD_EMP_PROJ
TO ROLE MANAGER;

-- Выдача привилегии EXECUTE на хранимую функцию GET_BEGIN_DATE
-- из схемы APP для роли MANAGER
GRANT EXECUTE ON FUNCTION APP.GET_BEGIN_DATE TO ROLE MANAGER;

-- Выдача привилегии EXECUTE на пакет APP_VAR из схемы APP
-- для всех пользователей
GRANT EXECUTE ON PACKAGE APP.APP_VAR TO PUBLIC;

-- Выдача привилегии EXECUTE на функцию GET_BEGIN_DATE из схемы APP
-- для пакета APP_VAR из схемы APP
GRANT EXECUTE ON FUNCTION APP.GET_BEGIN_DATE
TO PACKAGE APP.APP_VAR;
----
====

[[fblangref-security-grant-usage]]
=== Привилегия `USAGE`

Привилегия `USAGE` (использование) применима к схемам, а также другим объектам метаданных, таких как исключения и последовательности (генераторы).

[NOTE]
====
Привилегия `USAGE` также предусматривается для доменов, наборов символов (CHARACTER SET) и сортировок (COLLATION), но в настоящее время для объектов метаданных этих типов привилегия `USAGE` не проверяется. Это может быть изменено в следующих релизах, если покажется целесообразным.
====

Прежде всего привилегия `USAGE` необходима для использования схемы пользователем, который не является её владельцем. Привилегию `USAGE` на схему можно выдать также для роли или одного из объектов метаданных, который может быть грантополучателем. Например, если хранимая процедура внутри PSQL кода хочет получить доступ к объекту метаданных из другой схемы (не той в которой создана эта процедура), то этой процедуре необходимо выдать привилегию `USAGE` на эту схему.

Для автоматически создаваемой вместе с базой данных схемы `PUBLIC`, а также системной схемы `SYSTEM` уже выдана привилегия `USAGE` для пользователя `PUBLIC`.

Для использования последовательностей (генераторов) и исключений в пользовательских запросах, необходимо предоставить пользователю привилегию `USAGE` для этих объектов. Поскольку в Firebird хранимые процедуры и функции, триггеры и подпрограммы пакетов выполняются с привилегиями вызывающего пользователя, то при использовании таких объектов метаданных в них, может потребоваться назначить привилегию `USAGE` и для них.

[NOTE]
====
Привилегия `USAGE` даёт права только на приращения генераторов (последовательностей) с помощью функции `GEN_ID` или конструкции `NEXT VALUE FOR`. Оператор `SET GENERATOR` является аналогом оператора `ALTER SEQUENCE ... RESTART WITH`, которые относятся к DDL операторам. По умолчанию права на такие операции имеет только владелец генератора (последовательности). Права на установку начального значения любого генератора (последовательности) можно предоставить с помощью `GRANT ALTER ANY SEQUENCE`, что не рекомендуется для обычных пользователей.
====

[[fblangref-security-grant-usage-exmpl]]
==== Примеры предоставления привилегии `USAGE`

.Предоставление привилегии `USAGE`
[example]
====
[source,sql]
----
-- Выдача привилегии USAGE на схему MANAGEMENT для роли MANAGER
GRANT USAGE ON SCHEMA MANAGEMENT TO ROLE MANAGER;

-- Выдача привилегии USAGE на последовательность GEN_AGE из текущей схемы
-- для роли MANAGER
GRANT USAGE ON SEQUENCE GEN_AGE TO ROLE MANAGER;

-- Выдача привилегии USAGE на последовательность GEN_AGE из текущей схемы
-- для триггера TR_AGE_BI из текущей схемы
GRANT USAGE ON SEQUENCE GEN_AGE TO TRIGGER TR_AGE_BI;

-- Выдача привилегии USAGE на исключение E_ACCESS_DENIED из текущей схемы
-- для пакета PKG_BILL из текущей схемы
GRANT USAGE ON EXCEPTION E_ACCESS_DENIED
TO PACKAGE PKG_BILL;
----
====

[[fblangref-security-grant-ddl]]
=== DDL привилегии

По умолчанию создавать новые объекты метаданных могут только <<fblangref-security-administrators,Администраторы>> и владельцы схемы, в которой этот объект создаётся. Изменять и удалять объекты метаданных могут администраторы, владельцы схем, в которых расположен этот объект, и владельцы этих объектов. Выдача привилегий на создание, изменение или удаление объектов конкретного типа позволяет расширить этот список. Как известно объекты метаданных делятся на те которые всегда располагаются в одной из схем, и объекты метаданных, которые существуют вне схем (обычно на уровне базы данных).

[[fblangref-security-grant-ddl-privsyntax]]
.Синтаксис (предоставление DDL привилегий)
[listing,subs=+quotes]
----
GRANT <ddl_privileges>
  TO <grantee_list>
  [WITH GRANT OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<ddl_privileges> ::=
  {ALL [PRIVILEGES] | <ddl_privilege_list>}
  {[ON SCHEMA _schema_name_] <object_type> | <schemaless_object_type>}


<ddl_privilege_list> ::=
  <ddl_privilege> [, <ddl_privilege> ...]

<ddl_privilege> ::= CREATE | ALTER ANY | DROP ANY

<object_type> ::=
    CHARACTER SET | COLLATION | DOMAIN | EXCEPTION
  | FILTER | FUNCTION | GENERATOR | PACKAGE
  | PROCEDURE | ROLE | SEQUENCE | TABLE | VIEW

<schemaless_object_type> ::=
    FILTER | ROLE | SCHEMA

<db_ddl_privileges> ::=
  {ALL [PRIVILEGES] | <db_ddl_privilege_list>} DATABASE

<db_ddl_privilege_list> ::=
  <db_ddl_privilege> [, <db_ddl_privilege> ...]

<db_ddl_privilege> ::= CREATE | ALTER | DROP
----


.Список DDL привилегий
`CREATE`::
Разрешает создание объекта указанного типа метаданных.

`ALTER ANY`::
Разрешает изменение любого объекта указанного типа метаданных.

`DROP ANY`::
Разрешает удаление любого объекта указанного типа метаданных.

`ALL`::
Объединяет привилегии `CREATE`, `ALTER` и `DROP` на указанный тип объекта.

Для объектов метаданных, которые располагаются в схемах, вы можете указать схему с помощью предложения `ON SCHEMA`. Предоставляемые привилегии будут действовать только в указанное схеме. Если предложение `ON SCHEMA` опущено, то будут предоставлены привилегии для объектов метаданных указанного типа внутри текущей схемы.

Для объектов метаданных, которые располагаются вне схем, указывать схему не надо. Для таких объектов привилегии всегда будут действовать на уровне базы данных.

[NOTE]
====
Метаданные триггеров и индексов наследуют привилегии таблиц, которые владеют ими.
====

[[fblangref-security-grant-ddl-exmpl]]
==== Примеры предоставления DDL привилегий

.Предоставление привилегий на изменение метаданных
[example]
====
[source,sql]
----
-- Разрешение пользователю Joe создавать таблицы в схеме Main
GRANT CREATE TABLE ON SCHEMA Main TO Joe;

-- Разрешение пользователю Bob создавать таблицы в текущей схеме
GRANT CREATE TABLE TO Bob;

-- Разрешение пользователю Joe изменять любые процедуры в схеме Main
GRANT ALTER ANY PROCEDURE ON SCHEMA Main TO Joe;

-- Разрешение пользователю Bob удалять любые процедуры в текущей схеме
GRANT DROP ANY PROCEDURE TO Bob;

-- Разрешение для пользователя Alex создавать новые схемы
GRANT CREATE SCHEMA TO Alex;

-- Разрешение для пользователя Alex изменять любые роли
GRANT ALTER ANY ROLE TO Alex;
----
====

[[fblangref-security-grant-ddl-database]]
=== DDL привилегии для базы данных

Оператор назначения привилегий на создание, удаление и изменение базы данных имеет несколько отличную форму от оператора назначения DDL привилегий на другие объекты метаданных.

.Список DDL привилегий на базу данных
`CREATE`::
Разрешает создание базы данных.

`ALTER`::
Разрешает изменение текущей базы данных.

`DROP`::
Разрешает удаление текущей базы данных.

`ALL`::
Объединяет привилегии `ALTER` и `DROP` на базу данных.

Привилегия `CREATE DATABASE` является особым видом привилегий, поскольку она сохраняется в базе данных безопасности. Список пользователей имеющих привилегию `CREATE DATABASE` можно посмотреть в виртуальной таблице `SEC$DB_CREATORS`. Привилегию на создание новой базы данных могут выдавать только <<fblangref-security-administrators,Администраторы>> в базе данных безопасности.

Привилегии `ALTER DATABASE` и `DROP DATABASE` относятся только к текущей базе данных, тогда как DDL привилегии `ALTER ANY` и `DROP ANY` на другие объекты метаданных относятся ко всем объектам указанного типа внутри текущей базы данных. Привилегии на изменение и удаление текущей базы данных могут выдавать только <<fblangref-security-administrators,Администраторы>>.

[[fblangref-security-grant-db-ddl-exmpl]]
=== Примеры предоставления DDL привилегий на базу данных

.Разрешение пользователю Superuser создавать базы данных
[example]
====
[source,sql]
----
GRANT CREATE DATABASE TO USER Superuser;
----
====

.Разрешение пользователю Joe выполнять оператор `ALTER DATABASE` для текущей базы данных
[example]
====
[source,sql]
----
GRANT ALTER DATABASE TO USER Joe;
----
====

.Разрешение пользователю Fedor удалять текущую базу данных
[example]
====
[source,sql]
----
GRANT DROP DATABASE TO USER Fedor;
----
====

[[fblangref-security-grant-syspriv]]
=== Предоставление прав системным привилегиям


Благодаря поддержке системных привилегий в ядре, становится очень удобно предоставлять некоторые дополнительные привилегии пользователям уже имеющим какую-то системную привилегию. Для этих целей существует возможность использовать в качестве грантополучателя одну или несколько системных привилегий.

[[fblangref-security-grant-systemprv-example]]
=== Примеры предоставления прав системным привилегиям

[example]
====
Следующий оператор назначит все привилегии на представление `PLG$SRP_VIEW` из схемы `PLG$SRP`, используемое в плагине управления пользователями SRP, системной привилегии `USER_MANAGEMENT`.

[source,sql]
----
GRANT ALL ON PLG$SRP.PLG$SRP_VIEW TO SYSTEM PRIVILEGE USER_MANAGEMENT;
----
====

Описание системных привилегий вы можете посмотреть в <<fblangref-security-roles-create,CREATE ROLE>>

[[fblangref-security-grant-role]]
=== Назначение ролей

.Синтаксис (выдача ролей)
[listing,subs=+quotes]
----
GRANT <role_granted>
  TO <role_grantee_list>
  [WITH ADMIN OPTION]
  [{GRANTED BY | AS} [USER] _grantor_]

<role_granted> ::= [DEFAULT] _role_name_ [, [DEFAULT] _role_name_ ...]

<role_grantee_list> ::=
  <role_grantee> [, <role_grantee> ...]

<role_grantee> ::=
    [USER] _username_
  | [ROLE] _grantee_role_name_
----

Оператор `GRANT` может быть использован для назначения ролей для списка пользователей или ролей. В этом случае после предложения `GRANT` следует список ролей, которые будут назначены списку пользователей или ролей, указанному после предложения `TO`.

[[fblangref-security-grant-default-role]]
==== Ключевое слово `DEFAULT`

Если используется ключевое слово `DEFAULT`, то роль (роли) будет использоваться пользователем или ролью каждый раз, даже если она не была указана явно. При подключении пользователь получит привилегии всех ролей, которые были назначены пользователю с использованием ключевого слова `DEFAULT`. Если пользователь укажет свою роль при подключении, то получит привилегии этой роли (если она была ему назначена) и привилегии всех ролей назначенных ему с использованием ключевого слова `DEFAULT`.

[[fblangref-security-grant-role-admopt]]
==== Предложение `WITH ADMIN OPTION`

(((GRANT, WITH ADMIN OPTION)))
Необязательное предложение `WITH ADMIN OPTION` позволяет пользователям, указанным в списке пользователей, передавать свои роли другому пользователю или роли. Полномочия роли могут быть переданы кумулятивно, только если каждая роль в последовательности ролей назначена с использованием `WITH ADMIN OPTION`.

[[fblangref-security-grant-assignroles-exmpl]]
==== Примеры назначения ролей

.Назначение ролей для пользователей
[example]
====
[source,sql]
----
-- Назначение ролей DIRECTOR и MANAGER пользователю IVAN
GRANT DIRECTOR, MANAGER TO USER IVAN;

-- Назначение роли ADMIN пользователю ALEX
-- с возможностью назначить эту другим пользователям
GRANT MANAGER TO USER ALEX WITH ADMIN OPTION;
----
====

.Назначение ролей для пользователей с ключевым словом `DEFAULT`
[example]
====
[source,sql]
----
-- Назначение роли MANAGER пользователю JOHN
-- Привилегии роли будут автоматически назначаться пользователю
-- каждый раз при входе. В этом случае роль выступает в качестве группы.
GRANT DEFAULT MANAGER TO USER JOHN;

-- Теперь при входе пользователь JOHN автоматически получит привилегии
-- ролей MANAGER (см. предыдущий оператор) и DIRECTOR
GRANT DEFAULT DIRECTOR TO USER JOHN;
----
====

.Назначение ролей другим ролям
[example]
====
[source,sql]
----
-- Назначение роли MANAGER для роли DIRECTOR
-- с возможностью передачи роли MANAGER другим пользователям или ролям
GRANT MANAGER TO ROLE DIRECTOR WITH ADMIN OPTION;

-- Назначение роли ACCOUNTANT роли DIRECTOR
-- при входе в систему с ролью DIRECTOR полномочия роли ACCOUNTANT
-- будут также получены
GRANT DEFAULT ACCOUNTANT TO ROLE DIRECTOR;

-- Пользователь PETROV при входе автоматически получает
-- полномочия роли DIRECTOR. Эти полномочия будут включать также
-- полномочия роли ACCOUNTANT. Для получения полномочий роли MANAGER
-- необходимо указать эту роль при входе в систему или позже с
-- помощью оператора SET ROLE
GRANT DEFAULT ROLE DIRECTOR TO USER PETROV;
----
====

.См. также:
<<fblangref-security-revoke,REVOKE>>.
