[[fblangref-ddl-comment]]
= COMMENTS

Объекты базы данных и сама база данных могут содержать примечания. Это удобное средство документирования во время разработки базы данных и её поддержки.

[[fblangref-ddl-commenton]]
== `COMMENT ON`

.Назначение
Документирование метаданных.
(((COMMENT ON)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs="+quotes,macros"]
----
COMMENT ON <object> IS {'_sometext_' | NULL}
<object> ::=
    DATABASE
  | <basic-type> \[__schema-name__.]_objectname_
  | <schema-lees-type> _objectname_
  | USER _username_ [USING PLUGIN _plugin_name_]
  | COLUMN \[__schema-name__.]_relationname_._fieldname_
  | [PROCEDURE | FUNCTION] PARAMETER
    [_schema-name_.]\[__package_name__.]_routinename_._paramname_
  | {PROCEDURE | [EXTERNAL] FUNCTION}
    [_schema-name_.]\[__package_name__.]_routinename_
  | [GLOBAL] MAPPING _mappingname_

<basic-type> ::=
    CHARACTER SET
  | COLLATION
  | DOMAIN
  | EXCEPTION
  | GENERATOR
  | INDEX
  | PACKAGE
  | SEQUENCE
  | SCHEMA
  | TABLE
  | TRIGGER
  | VIEW

<schema-lees-type> ::=
    SCHEMA
  | FILTER
  | ROLE

----

[[fblangref-ddl-tbl-commenton]]
.Параметры оператора `COMMENT ON`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|sometext
|Текст комментария.

|basic-type
|Тип объекта метаданных, который расположен внутри схемы.

|schema-lees-type
|Тип объекта метаданных, который не имеет схемы.

|schema-name
|Имя схемы объекта метаданных.

|objectname
|Имя объекта метаданных.

|relationname
|Имя таблицы или представления.

|filedname
|Имя поля таблицы или представления.

|routinename
|Имя хранимой процедуры или функции.

|paramname
|Имя параметра хранимой процедуры или функции.

|package_name
|Имя пакета.

|username
|Имя пользователя.

|plugin_name
|Имя плагина управления пользователями.

|mappingname
|Имя отображения.
|===

Оператор `COMMENT ON` добавляет комментарии для объектов базы данных (метаданных). Комментарии при этом сохраняются в текстовые поля `RDB$DESCRIPTION` типа `BLOB` соответствующей системной таблицы (из этих полей клиентское приложение может просмотреть комментарии).

Для объектов метаданных которые располагаются в схемах есть возможность явно указывать схему объекта. Если указано только имя объекта метаданных, то его поиск производится в путях поиска (`SEARCH_PATH`). Комментарий будет добавлен к первому найденному объекту метаданных с заданным именем и типом среди схем перечисленных в путях поиска.

При добавлении комментария для пользователя вы можете уточнить в каком плагине управления пользователями он находится с помощью необязательного предложения `USING PLUGIN`. Если это предложение отсутствует, то предполагает что пользователь создан в плагине управления по умолчанию, то есть первого плагина указанного в параметре UserManager в файле `firebird.conf` или `databases.conf`.

[NOTE]
====
Если вы вводите пустой комментарий (''), то он будет сохранен в базе данных как `NULL`.
====

[[_fblangref_ddl_comment-who]]
=== Кто может добавить комментарий?

Выполнить оператор `COMMENT ON` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец объекта, для которого добавляется комментарий;
* Владелец схемы в которой содержится объект для которого добавляется комментарий;
* Пользователи с привилегией `ALTER ANY <object_type>` для объектов которые не имеют схемы;
* Пользователи с привилегией `ALTER ANY <object_type>` в схеме в которой располагается объект которому добавляется комментарий.


[[fblangref-ddl-commenton-examples]]
=== Примеры

.Добавление комментария для текущей базы данных.
[example]
====
[source,sql]
----
COMMENT ON DATABASE IS 'Это тестовая (''my.fdb'') БД';
----
====

.Добавление комментария для схемы APP.
[example]
====
[source,sql]
----
COMMENT ON SCHEMA APP IS 'Схема содержащая специфичные настройки приложения';
----
====

.Добавление комментария для таблицы.
[example]
====
[source,sql]
----
-- добавляется комментарий к первой найденной в путях поиска таблице METALS
COMMENT ON TABLE METALS IS 'Справочник металлов';
----
====

.Добавление комментария для таблицы из схемы PRODUCTION.
[example]
====
[source,sql]
----
COMMENT ON TABLE PRODUCTION.METALS IS 'Справочник металлов';
----
====

.Добавление комментария для поля таблицы.
[example]
====
[source,sql]
----
-- добавляется комментарий к столбцу первой найденной в путях поиска таблице METALS
COMMENT ON COLUMN METALS.ISALLOY
IS '0 = чистый металл, 1 = сплав';
----
====

.Добавление комментария для поля таблицы из схемы PRODUCTION.
[example]
====
[source,sql]
----
COMMENT ON COLUMN PRODUCTION.METALS.ISALLOY
IS '0 = чистый металл, 1 = сплав';
----
====

.Добавление комментария для параметра процедуры.
[example]
====
[source,sql]
----
-- добавляется комментарий к параметру первой найденной в путях поиска процедуры ADD_EMP_PROJ
COMMENT ON PARAMETER ADD_EMP_PROJ.EMP_NO
IS 'Код сотрудника';
----
====

.Добавление комментария для параметра процедуры из схемы MANAGEMENT.
[example]
====
[source,sql]
----
COMMENT ON PARAMETER MANAGEMENT.ADD_EMP_PROJ.EMP_NO
IS 'Код сотрудника';
----
====

.Добавление комментария для пакета, его процедур и функций, и их параметров.
[example]
====
[source,sql]
----
-- добавляется комментарий к первому найденному в путях поиска пакету APP_VAR

COMMENT ON PACKAGE APP_VAR IS 'Переменные приложения';

COMMENT ON FUNCTION APP_VAR.GET_DATEBEGIN
IS 'Возвращает дату начала периода';

COMMENT ON PROCEDURE APP_VAR.SET_DATERANGE
IS 'Установка диапазона дат';

COMMENT ON
PROCEDURE PARAMETER APP_VAR.SET_DATERANGE.ADATEBEGIN
IS 'Дата начала';
----
====

.Добавление комментария для пакета, его процедур и функций, и их параметров из схемы APP.
[example]
====
[source,sql]
----
COMMENT ON PACKAGE APP.APP_VAR IS 'Переменные приложения';

COMMENT ON FUNCTION APP.APP_VAR.GET_DATEBEGIN
IS 'Возвращает дату начала периода';

COMMENT ON PROCEDURE APP.APP_VAR.SET_DATERANGE
IS 'Установка диапазона дат';

COMMENT ON
PROCEDURE PARAMETER APP.APP_VAR.SET_DATERANGE.ADATEBEGIN
IS 'Дата начала';
----
====

.Добавление комментария для пользователя.
[example]
====
[source,sql]
----
COMMENT ON USER BOB35 IS 'Это Боб из плагина по умолчанию';

COMMENT ON USER JOHN USING PLUGIN Legacy_UserManager
IS 'Это Джон из плагина Legacy_UserManager';
----
====

