[[fblangref-ddl-package]]
= PACKAGE

Пакет -- группа процедур и функций, которая представляет собой один объект базы данных.

Пакеты Firebird состоят из двух частей: заголовка (ключевое слово `PACKAGE`) и тела (ключевые слова `PACKAGE BODY`). Такое разделение очень сильно напоминает модули Delphi, заголовок соответствует интерфейсной части, а тело -- части реализации.

Сначала создаётся заголовок (`CREATE PACKAGE`), а затем -- тело (<<fblangref-ddl-package-body-create,CREATE PACKAGE BODY>>).

Пакеты располагаются внутри схем базы данных.

[[fblangref-ddl-package-create]]
== `CREATE PACKAGE`

.Назначение
Создание заголовка пакета.
(((CREATE PACKAGE)))

.Доступно в
DSQL

[[fblangref-ddl-pkg-create-syntax]]
.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
CREATE PACKAGE [IF NOT EXISTS] [ _pkg-schema_ <period> ] _package_name_
[<rights clause>]
AS
BEGIN
  [<package_item> ...]
END

<rights clause> ::=
  SQL SECURITY {DEFINER | INVOKER}

<package_item> ::=
    <function declaration>;
  | <aggregate function declaration>;
  | <procedure declaration>;
  | <constant declaration>;
  | <temporary table declaration>;

<function declaration> ::=
  FUNCTION _func_name_ [(<in_params>)]
  RETURNS <type> [NOT NULL]
    [COLLATE [ _coll-schema_ <period> ] _collation_]
  [ [NOT] DETERMINISTIC ]

<aggregate function declaration> ::=
  AGGREGATE FUNCTION _func_name_ [(<in_params>)]
  RETURNS <type> [NOT NULL]
    [COLLATE [ _coll-schema_ <period> ] _collation_]

<procedure declaration> ::=
  PROCEDURE _proc_name_ [(<in_params>)]
  [RETURNS (<out_params>)]

<constant declaration> ::=
  CONSTANT _const_name_ <type> = <constant expression>

<temporary table declaration> ::=
  TEMPORARY TABLE _table_name_
  (
    <column_definition> [, ...]
  )
  [ON COMMIT {DELETE | PRESERVE} ROWS]
  [{[UNIQUE] [ASC | DESC] INDEX _index_name_ (_column_name_)}...]

<in_params> ::= <inparam> [, <inparam> ...]

<inparam> ::= <param_decl> [{= | DEFAULT} <value>]

<value> ::=  {_literal_ | NULL | _context_var_}

<out_params> ::= <outparam> [, <outparam> ...]

<outparam>  ::=  <param_decl>

<param_decl> ::= _paramname_ <type> [NOT NULL] [COLLATE [ _coll-schema_ <period> ] _collation_]

<type> ::=
    <datatype>
  | [TYPE OF] [ _dom-schema_ <period> ] _domain_name_
  | TYPE OF COLUMN [ _rel-schema_ <period> ] _rel_._col_

<datatype> ::=
    <scalar_datatype> | <blob_datatype>

<scalar_datatype> ::=  См. <<fblangref-datatypes-syntax-scalar,Синтаксис скалярных типов данных>>

<blob_datatype> ::= См. <<fblangref-datatypes-syntax-blob,Синтаксис типа данных BLOB>>
----

[[fblangref-ddl-tbl-createpkg]]
.Параметры оператора `CREATE PACKAGE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|pkg-schema
|Имя схемы пакета. Если не указано, то пакет создаётся в текущей схеме.

|package_name
|Имя пакета. Может содержать до 63 символов.

|function declaration
|Объявление скалярной функции.

|aggregate function declaration
|Объявление агрегатной функции.

|procedure declaration
|Объявление процедуры.

|constant declaration
|Объявление константы.

|temporary table declaration
|Объявление временной таблицы.

|proc_name
|Имя процедуры. Может содержать до 63 символов.

|func_name
|Имя функции. Может содержать до 63 символов.

|const_name
|Имя константы. Может содержать до 63 символов.

|table_name
|Имя временной таблицы. Может содержать до 63 символов.

|index_name
|Имя индекса временной таблицы. Может содержать до 63 символов.

|column_name
|Имя столбца временной таблицы. Может содержать до 63 символов.

|inparam
|Описание входного параметра.

|outparam
|Описание выходного параметра.

|literal
|Литерал, совместимый по типу с параметром.

|context_var
|Любая контекстная переменная, тип которой совместим с типом параметра.

|paramname
|Имя входного или выходного параметра процедуры/функции. Может содержать до 63 символов. Имя параметра должно быть уникальным среди входных и выходных параметров процедуры/функции, а также её локальных переменных.

|datatype
|Тип данных SQL.

|coll-schema
|Имя схемы сортировки (сравнения). Если не указано, то сортировка будет найдена в пути поиска.

|collation
|Имя сортировки (сравнения).

|dom-schema
|Имя схемы домена. Если не указано, то домен будет найден в пути поиска.

|domain_name
|Имя домена.

|rel-schema
|Имя схемы таблицы или представления. Если не указано, то таблица или представление будут найдены в пути поиска.

|rel
|Имя таблицы или представления.

|col
|Имя столбца таблицы или представления.

|constant expression
|Выражение для инициализации константы.
|===

Оператор `CREATE PACKAGE` создаёт новый заголовок пакета. Если перед именем пакета указана схема, то пакет будет создан в указанной схеме, в противном случае пакет будет создан в текущей схеме (первая валидная схема в пути поиска).

Имя пакета должно быть уникальным среди имён всех пакетов внутри заданной (текущей) схемы.

[IMPORTANT]
====
Поскольку `CREATE PACKAGE` является DDL оператором, то после того как создаваемый пакет привязан к схеме во время подготовки оператора, путь поиска неявно и временно изменяется. Эта корректировка устанавливает путь поиска на схему пакета. Кроме того, схема `SYSTEM` добавляется как последняя схема в путь поиска. Это обозначает, что имена объектов метаданных, используемые внутри оператора `CREATE PACKAGE` будут разрешаться относительно этого нового пути поиска.
====

Если используется предложение `IF NOT EXISTS`, то оператор `CREATE PACKAGE` попытается создать новый заголовок пакета без выдачи ошибки, если он уже существует. DDL триггеры не будут запускаться, если заголовок пакета уже существует.

Процедуры, функции, константы и временные таблицы, объявленные в заголовке пакета, доступны вне тела пакета через полный идентификатор имён (`_package_name_._procedure_name_`, `_package_name_._function_name_` и `_package_name_._constant_name_`, `_package_name_._table_name_`). Процедуры и функции, определенные в теле пакета, но не объявленные в заголовке пакета, не видны вне тела пакета.

Константы и временные таблицы объявленные в теле пакета не видны вне тела пакета. Константа или временная таблица объявленная в заголовке пакета, не может быть повторно объявлена в теле пакета.

Имена процедур, функций, констант и временных таблиц, объявленные в заголовке пакета, должны быть уникальны среди имён процедур, функций, констант и временных таблиц, объявленных в заголовке и теле пакета.

[[fblangref-ddl-package-create-sql-security]]
=== Привилегии выполнения

(((CREATE PACKAGE, SQL SECURITY)))
Необязательное предложение `SQL SECURITY` позволяет задать с какими привилегиями выполняется процедуры и функции пакета. Если выбрана опция `INVOKER`, то процедуры и функции пакета выполняются с привилегиями вызывающего пользователя. Если выбрана опция `DEFINER`, то процедуры и функции пакета выполняется с привилегиями определяющего пользователя (владельца пакета). Эти привилегии будут дополнены привилегиями выданные самому пакету с помощью оператора `GRANT`. По умолчанию процедуры и функции пакета выполняются с привилегиями вызывающего пользователя. Переопределять привилегии выполнения для процедур и функций пакета запрещено.

[TIP]
====
Привилегии выполнения по умолчанию для вновь создаваемых объектов метаданных можно изменить с помощью оператора

[listing]
----
ALTER DATABASE SET DEFAULT SQL SECURITY {DEFINER | INVOKER}
----
====

[[fblangref-ddl-package-term]]
=== Терминатор оператора

Некоторые редакторы SQL-операторов -- в частности утилита `isql` из комплекта Firebird, и возможно некоторые сторонние редакторы -- используют внутреннее соглашение, которое требует, чтобы все операторы были завершены с точкой с запятой.

Это создает конфликт с синтаксисом PSQL при кодировании в этих средах. Если вы не знакомы с этой проблемой и её решением, пожалуйста, изучите детали в главе PSQL в разделе, озаглавленном
<<fblangref-psql-setterm,Изменение терминатора в `isql`>>.

[[fblangref-ddl-package-create_params]]
=== Параметры процедур и функций

У каждого параметра указывается тип данных. Кроме того, для параметра можно указать ограничение `NOT NULL`, тем самым запретив передавать в него значение `NULL`.

Для параметра строкового типа существует возможность задать порядок сортировки с помощью предложения `COLLATE`.

[[fblangref-ddl-package-create-params-in]]
==== Входные параметры

Входные параметры заключаются в скобки после имени хранимой процедуры. Они передаются в процедуру по значению, то есть любые изменения входных параметров внутри процедуры никак не повлияет на значения этих параметров в вызывающей программе.

Входные параметры могут иметь значение по умолчанию. Параметры, для которых заданы значения, должны располагаться в конце списка параметров.

[[fblangref-ddl-package-create-params-out]]
==== Выходные параметры

Для хранимых процедур список выходных параметров задаётся в необязательное предложение `RETURNS`.

Для хранимых функций в обязательном предложении `RETURNS` задаётся тип возвращаемого значения.

[[fblangref-ddl-package-create-params-domain]]
==== Использование доменов при объявлении параметров

В качестве типа параметра можно указать имя домена. В этом случае параметр будет наследовать все характеристики домена.

Если перед названием домена дополнительно используется предложение `TYPE OF`, то используется только тип данных домена -- не проверяются его ограничения `NOT NULL` и `CHECK` (если они есть), а также не используется значение по умолчанию. Если домен текстового типа, то всегда используется его набор символов и порядок сортировки.

[[fblangref-ddl-package-create-params-typeofcolumn]]
==== Использование типа столбца при объявлении параметров

Входные и выходные параметры можно объявлять, используя тип данных столбцов существующих таблиц и представлений. Для этого используется предложение `TYPE OF COLUMN`, после которого указывается имя таблицы или представления и через точку имя столбца.

При использовании `TYPE OF COLUMN` наследуется только тип данных, а в случае строковых типов ещё и набор символов, и порядок сортировки. Ограничения и значения по умолчанию столбца никогда не используются.

[[fblangref-ddl-package-create-func-agg]]
=== Агрегатные функции

Функция может быть объявлена как агрегатная `AGGREGATE FUNCTION` или скалярная `FUNCTION`. Если функция объявлена как агрегатная, то она должна быть реализована как агрегатная, а не скалярная.

[[fblangref-ddl-package-create-func-determ]]
=== Детерминированные функции

Необязательное предложение `DETERMINISTIC` в объявлении функции указывает, что функция детерминированная. Детерминированные функции каждый раз возвращают один и тот же результат, если предоставлять им один и тот же набор входных значений. Недетерминированные функции могут возвращать каждый раз разные результаты, даже если предоставлять им один и тот же набор входных значений. Если для функции указано, что она является детерминированной, то такая функция не вычисляется заново, если она уже была вычислена однажды с данным набором входных аргументов, а берет свои значения из кэша метаданных (если они там есть).

[NOTE]
====
На самом деле в текущей версии Firebird, не существует кэша хранимых функций с маппингом входных аргументов на выходные значения.

Указание инструкции `DETERMINISTIC` на самом деле нечто вроде "`обещания`", что код функции будет возвращать одно и то же. В данный момент детерминистическая функция считается инвариантом и работает по тем же принципам, что и другие инварианты. То есть вычисляется и кэшируется на уровне текущего выполнения данного запроса.
====

Ключевое слово `DETERMINISTIC` допустимо указывать только для скалярных функций.

[[fblangref-ddl-package-create-const]]
=== Константы

Константа пакета -- это значение, инициализированное константным выражением.

Объявление константы может быть как в заголовке, так и в теле пакета. Если константы объявлена в теле пакета, то на неё можно ссылаться из других процедур и функций этого пакета ниже точки объявления.

Если константы объявлена в заголовке пакета, то она доступна как в теле этого пакета, так и за его пределами.

Константное выражение определяется простым правилом: его значение не изменяется после перекомпиляции.

Допускаются следующие выражения:

* Литерал любого скалярного типа данных
* `NULL`

Следующие выражения допустимы только в том случае, если все операнды являются константами:

. Арифметические операции, конкатенация строк, унарные плюс/минус
. `CAST`, `COALESCE`, `DECODE`, `EXTRACT`, `UPPER`, `LOWER`, `SUBSTRING`
. `BIT_LENGTH`, `CHAR_LENGTH`, `CHARACTER_LENGTH`, `OCTET_LENGTH`
. `TRIM`, `LTRIM`, `RTRIM`, `BTRIM`
. `NULLIF`, `IIF`, `CASE`
. Другие константы
. `ABS`, `ACOS`, `ASIN`, `ASINH`, `ATAN`, `ATANH`, `ATAN2`, `SIGN`, `SIN`, `SINH`, `TAN`, `TANH`, `COS`, `COT`
. `BIN_*`, `CEIL`, `CEILING`, `FLOOR`, `ROUND`, `MOD`, `EXP`, `MAXVALUE`, `MINVALUE`, `POWER`, `COMPARE_DECFLOAT`, `TRUNC`, `SQRT`
. `GREATEST`, `LEAST`
. `LN`, `LOG`, `LOG10`, `PI`
. `MAKE_DBKEY`, `OVERLAY`, `NORMALIZE_DECFLOAT`, `QUANTIZE`, `TOTALORDER`
. `HEX_DECODE`, `HEX_ENCODE`, `BASE64_DECODE`, `BASE64_ENCODE`, `RSA_DECRYPT`, `RSA_ENCRYPT`, `RSA_SIGN_HASH`, `RSA_VERIFY_HASH`
. `DECRYPT`, `ENCRYPT`, `HASH`, `CRYPT_HASH`
. `LEFT`, `REPLACE`, `REVERSE`, `RIGHT`, `LPAD`, `RPAD`, `POSITION`
. `CHAR_TO_UUID`, `UNICODE_CHAR`, `UNICODE_VAL`, `UUID_TO_CHAR`, `ASCII_CHAR`, `ASCII_VAL`
. `LAST_DAY`, `FIRST_DAY`, `DATEADD`, `DATEDIFF`

Например, выражение `CAST(PI() / 2 as CHAR(50))` является константой.

Однако выражение `EXTRACT(YEAR FROM CURRENT_DATE)` таковым не является (`CURRENT_DATE` изменяется в зависимости от времени вычисления).

Пользовательские функции не могут быть использованы для инициализации константных выражений, даже если они является детерминированными.

[[fblangref-ddl-package-create-temp-table]]
=== Временные таблицы

Начиная с Firebird 6.0 поддерживается объявление временных таблиц внутри SQL-пакетов. Такие временные таблицы называются упакованными временными таблицами (Packaged Temporary Table).

Внутри они хранятся как постоянные метаданные временных таблиц, принадлежащие пакету и идентифицируемые с помощью `RDB$PACKAGE_NAME`. Их данные остаются временными: локальными для транзакций при `ON COMMIT DELETE ROWS` и локальными для соединений при `ON COMMIT DELETE ROWS`.

* `ON COMMIT DELETE ROWS` (по умолчанию): данные таблицы являются локальными для транзакции и удаляются по завершении транзакции.
* `ON COMMIT PRESERVE ROWS`: данные таблицы являются локальными для соединения и сохраняются между транзакциями в рамках одного и того же соединения.

Определение таблицы является частью метаданных пакета и сохраняется, как и другие члены пакета; данные таблицы остаются
временными.

==== Видимость временных таблиц пакета и разрешение имён

Видимость зависит от места объявления таблицы:

* Таблицы, объявленные в `CREATE PACKAGE` (заголовок пакета), являются открытыми членами пакета.
* Таблицы, объявленные в `CREATE PACKAGE BODY` (тело пакета), являются закрытыми для тела этого пакета.
* Неквалифицированные ссылки на соответствующее имя объявленной таблицы внутри подпрограмм пакета разрешаются в таблицу пакета.

Права доступа:

* Права доступа к временным таблицам в пакете привязаны к самому пакету, а не к отдельным таблицам в пакете.
* Для прямого доступа к общедоступным таблицам заголовка требуется соответствующая привилегия пакета для запрашиваемой операции, например, `SELECT`, `INSERT`, `UPDATE` или `DELETE`.
* Доступ к закрытым таблицам тела запроса невозможен извне с помощью прав доступа пакета.
* Если пакет создан в непубличной схеме, вызывающей стороне также требуется привилегия `USAGE` для этой схемы.

==== Индексы для временных таблиц пакета

* Индексы для временных таблиц, упакованных в пакет, должны быть объявлены непосредственно в `TEMPORARY TABLE`.
* Автономные команды DDL для индексов не допускаются для упакованных таблиц: `CREATE INDEX`, `ALTER INDEX`, `DROP INDEX`, `SET STATISTICS INDEX`.

==== Изоляция имён временных таблиц

Имена таблиц изолируются контекстом пакета.

* Разные пакеты могут объявлять таблицы с одинаковым именем.
* Имя таблицы в пакете может также совпадать с обычным именем таблицы в той же схеме.

Внутри подпрограмм пакета предпочтение отдается объявлению, локальному для пакета.

[[fblangref-ddl-package-create-who]]
=== Кто может создать пакет?

Выполнить оператор `CREATE PACKAGE` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец схемы в которой создаётся пакет;
* Пользователи с привилегией `CREATE PACKAGE` для схемы в которой создаётся пакет.

Пользователь, создавший заголовок пакета становится владельцем пакета.

[[fblangref-ddl-package-create-examples]]
=== Примеры

.Создание заголовка пакета в текущей схеме
[example]
====
[source,sql]
----
CREATE PACKAGE APP_VAR
AS
BEGIN
  -- публичные константы пакета
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  -- публичные функции пакета
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  -- публичные процедуры пакета
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----

То же самое, но процедуры и функции пакета будут выполняться с правами определяющего пользователя (владельца пакета).

[source,sql]
----
CREATE PACKAGE APP_VAR
SQL SECURITY DEFINER
AS
BEGIN
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----
====

.Создание заголовка пакета в схеме APP
[example]
====
[source,sql]
----
CREATE PACKAGE APP.APP_VAR
AS
BEGIN
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----
====

.Создание пакета с публичными константами
[example]
====
[source,sql]
----
CREATE OR ALTER PACKAGE TYPE_LIMITS
AS
BEGIN
  CONSTANT MIN_BOOLEAN_VALUE BOOLEAN = FALSE;
  CONSTANT MAX_BOOLEAN_VALUE BOOLEAN = TRUE;

  CONSTANT MIN_SMALLINT_VALUE SMALLINT = -BIN_SHL(1, 15);
  CONSTANT MAX_SMALLINT_VALUE SMALLINT = BIN_SHL(1, 15) - 1;

  CONSTANT MIN_INTEGER_VALUE INTEGER = -BIN_SHL(1, 31);
  CONSTANT MAX_INTEGER_VALUE INTEGER = BIN_SHL(1, 31) - 1;

  CONSTANT MIN_BIGINT_VALUE BIGINT = -BIN_SHL(CAST(1 AS INT128), 63);
  CONSTANT MAX_BIGINT_VALUE BIGINT = BIN_SHL(CAST(1 AS INT128), 63) - 1;

  CONSTANT MIN_INT128_VALUE INT128 = -BIN_SHL(CAST(1 AS INT128), 126) * 2;
  CONSTANT MAX_INT128_VALUE INT128 = BIN_SHL(CAST(1 AS INT128), 126) - 1 + BIN_SHL(CAST(1 AS INT128), 126);

  CONSTANT MIN_DATE_VALUE DATE = DATE '0001-01-01';
  CONSTANT MAX_DATE_VALUE DATE = DATE '9999-12-31';

  CONSTANT MIN_TIME_VALUE TIME = TIME '00:00';
  CONSTANT MAX_TIME_VALUE TIME = TIME '23:59:59.9999';

  CONSTANT MIN_TIMESTAMP_VALUE TIMESTAMP = TIMESTAMP '0001-01-01 00:00';
  CONSTANT MAX_TIMESTAMP_VALUE TIMESTAMP = TIMESTAMP '9999-12-31 23:59:59.9999';
END
----
====

.Создание заголовка пакета с публичной временной таблицей
[example]
====
[source,sql]
----
SET TERM !;

RECREATE PACKAGE PKG
AS
BEGIN
  -- объявление публичной временной таблицы пакета
  TEMPORARY TABLE T_PUB(
    ID INTEGER
  )
  ON COMMIT PRESERVE ROWS
  INDEX IDX_T_PUB_ID (ID);

  PROCEDURE P1(N INTEGER);
  PROCEDURE P2 RETURNS (N INTEGER);
END!

SET TERM ;!
----
====

.Создание заголовка пакета с агрегатными функциями
[example]
====
[source,sql]
----
SET TERM !;

CREATE PACKAGE PUBLIC.OPTIMIZER_UTILS
AS
BEGIN
  /**
   * Расчёт селективности конъюнктов предикатов (предикаты объединённые AND).
   * Предикаты считаются некоррелированными.
   * Общая селективность оценивается как произведения селективностей предикатов.
   *
   * Подход использовался в Firebird 5.0 и более ранних.
   */
  AGGREGATE FUNCTION CONJ_SELECTIVITY_FB50 (A_SELECTIVITY DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION;

  /**
   * Расчёт селективности конъюнктов предикатов (предикаты объединённые AND).
   * Предикаты считаются частично коррелированными.
   * Используется алгоритм Exponential backoff. Суть алгоритма в следующем:
   * Предикаты сортируются по селективности от лучшей к худшей (меньшей к большей),
   * а затем общая селективность рассчитывается по формуле:
   *
   * S = S1 * S2^1/2 * S3^1/4 ... SN^1/2N
   *
   * Подход используется начиная с Firebird 6.0.
   */
  AGGREGATE FUNCTION CONJ_SELECTIVITY_FB60 (A_SELECTIVITY DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION;
END!

SET TERM ;!
----
====

.См. также:
<<fblangref-ddl-package-body-create,CREATE PACKAGE BODY>>,
<<fblangref-ddl-package-alter,ALTER PACKAGE>>,
<<fblangref-ddl-package-drop,DROP PACKAGE>>.

[[fblangref-ddl-package-alter]]
== `ALTER PACKAGE`

.Назначение
Изменение заголовка пакета.
(((ALTER PACKAGE)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
ALTER PACKAGE [ _pkg-schema_ <period> ] _package_name_
{   <alter-package-header>
  | <alter-package-option> }

<alter-package-header> :==
  [SQL SECURITY {DEFINER | INVOKER}]
  AS
  BEGIN
    [<package_item> ...]
  END

<alter-package-option> ::=
    SQL SECURITY {INVOKER | DEFINER}
  | DROP SQL SECURITY

Подробнее см. <<fblangref-ddl-pkg-create-syntax,CREATE PACKAGE>>
----

Оператор `ALTER PACKAGE` изменяет заголовок пакета. Позволяется изменять количество и состав процедур и функций, их входных и выходных параметров. При этом исходный код тела пакета сохраняется. Состояние соответствия тела пакета его заголовку отображается в столбце `RDB$PACKAGES.RDB$VALID_BODY_FLAG`.

Если указано только имя пакета, то его поиск производится в путях поиска (`SEARCH_PATH`). Будет изменён первый найденный пакет с заданным именем среди схем перечисленных в путях поиска.

[[fblangref-ddl-package-alter_sql_security]]
=== Привилегии выполнения

(((ALTER PACKAGE, SQL SECURITY)))
Оператор `ALTER PACKAGE` позволяет изменить привилегии выполнения пакет без указания остальных определений в заголовке пакета. Для установки привилегий выполнения используется предложение `SQL SECURITY` с одной из опций: `INVOKER` или `DEFINER`. Если необходимо удалить привилегии выполнения пакета укажите предложение `DROP SQL SECURITY`.

[[fblangref-ddl-package-alter_who]]
=== Кто может изменить заголовок пакета?

Выполнить оператор `ALTER PACKAGE` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец пакета;
* Владелец схемы в которой расположен пакет;
* Пользователи с привилегией `ALTER ANY PACKAGE` для схемы в которой расположен пакет.

[[fblangref-ddl-package-alter_examples]]
==== Примеры

.Изменение заголовка пакета
[example]
====
[source,sql]
----
ALTER PACKAGE APP_VAR
AS
BEGIN
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----
====

.Изменение только привилегий выполнения пакета
[example]
====
[source,sql]
----
-- Устанавливает PSQL пакету, что он будет выполнятся
-- с привилегиями вызывающего пользователя.
ALTER PACKAGE APP_VAR SQL SECURITY INVOKER;
-- Устанавливает PSQL пакету, что он будет выполнятся
-- с привилегиями определяющего пользователя (владельца пакета).
ALTER PACKAGE APP_VAR SQL SECURITY DEFINER;
-- Удаляет привилегии выполнения для PSQ пакета.
-- После выполнения этого оператора привилегии выполнения будут унаследованы
-- от схемы, в которой создан этот PSQL пакет.
ALTER PACKAGE APP_VAR DROP SQL SECURITY;
----
====

.См. также:
<<fblangref-ddl-package-alter,CREATE PACKAGE>>,
<<fblangref-ddl-package-drop,DROP PACKAGE>>,
<<fblangref-ddl-package-body-recreate,RECREATE PACKAGE BODY>>.

[[fblangref-ddl-package-createoralter]]
== `CREATE OR ALTER PACKAGE`

.Назначение
Создание нового или изменение существующего заголовка пакета.
(((CREATE OR ALTER PACKAGE)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
CREATE OR ALTER PACKAGE [ _pkg-schema_ <period> ] _package_name_
[<rights clause>]
AS
BEGIN
  [<package_item> ...]
END

<package_item> ::=
    <function declaration>;
  | <procedure declaration>;
  | <constant declaration>;
  | <temporary table declaration>;

Подробнее см. <<fblangref-ddl-pkg-create-syntax,CREATE PACKAGE>>
----

Оператор `CREATE OR ALTER PACKAGE` создаёт новый или изменяет существующий заголовок пакета. Если заголовок пакета не существует, то он будет создан с использованием предложения `CREATE PACKAGE`. Если он уже существует, то он будет изменен и перекомпилирован, при этом существующие привилегии и зависимости сохраняются.

Пакет создаётся или изменяется относительно указанной схемы. Если указано только имя пакета, то его создание или изменение происходит в текущей схеме (первая валидная схема в путях поиска).

[[fblangref-ddl-package-createoralter-examples]]
=== Примеры

.Создание нового или изменение существующего заголовка пакета
[example]
====
[source,sql]
----
CREATE OR ALTER PACKAGE APP_VAR
AS
BEGIN
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----
====

.См. также:
<<fblangref-ddl-package-alter,CREATE PACKAGE>>,
<<fblangref-ddl-package-alter,ALTER PACKAGE>>,
<<fblangref-ddl-package-body-recreate,RECREATE PACKAGE BODY>>.

[[fblangref-ddl-package-drop]]
== `DROP PACKAGE`

.Назначение
Удаление заголовка пакета.
(((DROP PACKAGE)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes"]
----
DROP PACKAGE [IF EXISTS] [ _pkg-schema_ <period> ] _package_name_
----

.Параметры оператора `DROP PACKAGE`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|pkg-schema
|Имя схемы пакета. Если не указано, то пакет будет найден в пути поиска.

|package_name
|Имя пакета.

|===

Оператор `DROP PACKAGE` удаляет существующий заголовок пакета. Перед удалением заголовка пакета (`DROP PACKAGE`), необходимо выполнить удаление тела пакета (`DROP PACKAGE BODY`), иначе будет выдана ошибка. Если от заголовка пакета существуют зависимости, то при попытке удаления такого заголовка будет выдана соответствующая ошибка.

Если указано только имя пакета, то его поиск производится в путях поиска (`SEARCH_PATH`). Будет удалён первый найденный пакет с заданным именем среди схем перечисленных в путях поиска.

Если используется предложение `IF EXISTS`, то оператор `DROP PACKAGE` попытается удалить заголовок пакета без выдачи ошибки, если его не существует. DDL триггеры не будут запускаться, если заголовок пакета не существует.

[[fblangref-ddl-package-drop-who]]
=== Кто может удалить заголовок пакета?

Выполнить оператор `DROP PACKAGE` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец пакета;
* Владелец схемы в которой расположен пакет;
* Пользователи с привилегией `DROP ANY PACKAGE` для схемы в которой расположен пакет.


[[fblangref-ddl-package-drop-examples]]
=== Примеры

.Удаление заголовка пакета
[example]
====
[source,sql]
----
DROP PACKAGE APP_VAR;
----
====

.Удаление заголовка пакета, если он существует
[example]
====
[source,sql]
----
DROP PACKAGE IF EXISTS APP_VAR;
----
====

.См. также:
<<fblangref-ddl-package-alter,CREATE PACKAGE>>,
<<fblangref-ddl-package-alter,ALTER PACKAGE>>,
<<fblangref-ddl-package-body-drop,DROP PACKAGE BODY>>.

[[fblangref-ddl-package-recreate]]
== `RECREATE PACKAGE`

.Назначение
Создание нового или пересоздание существующего заголовка пакета.
(((RECREATE PACKAGE)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
RECREATE PACKAGE [ _pkg-schema_ <period> ] _package_name_
[<rights clause>]
AS
BEGIN
  [<package_item> ...]
END

<package_item> ::=
    <function declaration>;
  | <procedure declaration>;
  | <constant declaration>;
  | <temporary table declaration>;

Подробнее см. <<fblangref-ddl-pkg-create-syntax,CREATE PACKAGE>>
----

Оператор `RECREATE PACKAGE` создаёт новый или пересоздаёт существующий заголовок пакета. Если заголовок пакета с таким именем уже существует в указанной (текущей) схеме, то оператор попытается удалить его и создать новый заголовок пакета. Пересоздать заголовок пакета невозможно, если у существующей заголовка пакета имеются зависимости или существует тело этого пакета. После пересоздания заголовка пакета привилегии на выполнение подпрограмм пакета и привилегии самого пакета не сохраняются.

Пакет создаётся или пересоздаётся относительно указанной схемы. Если указано только имя пакета, то его создание или пересоздание происходит в текущей схеме (первая валидная схема в путях поиска).

[[fblangref-ddl-package-recreate-examples]]
=== Примеры

.Создание нового или пересоздание существующего заголовка пакета
[example]
====
[source,sql]
----
RECREATE PACKAGE APP_VAR
AS
BEGIN
  CONSTANT MIN_DATE DATE = DATE '1900-01-01';
  CONSTANT MAX_DATE DATE = DATE '2100-12-31';

  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC;
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC;

  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE DEFAULT CURRENT_DATE);
END
----
====

.См. также:
<<fblangref-ddl-package-alter,CREATE PACKAGE>>,
<<fblangref-ddl-package-drop,DROP PACKAGE>>,
<<fblangref-ddl-package-body-recreate,RECREATE PACKAGE BODY>>.

