[[fblangref-ddl-schema]]
= SCHEMA

Схемы позволяют логически группировать объекты базы данных (такие как таблицы, представления и индексы), обеспечивая четкую структуру базы данных.  В основном они используются для двух целей:

* Схемы для организации объектов базы данных
+
Схемы помогают в модульной организации объектов базы данных, что упрощает управление и поддержку базы данных. Разделив базу данных на разные схемы, разработчики и администраторы могут сосредоточиться на определенных областях,
улучшая масштабируемость команды и снижая сложность.
+
Например, схема `SYSTEM` разделяет объекты, созданные двумя различными группами (основная команда СУБД Firebird и пользователи Firebird). Пользователи Firebird могут организовывать объекты в настраиваемых схемах, таких как `FINANCE` и `MARKETPLACE`.

* Схемы для изоляции данных
+
В многопользовательских приложениях схемы могут обеспечивать изоляцию данных для разных клиентов или арендаторов. Назначая уникальную схему каждому арендатору, таблицы и другие объекты могут иметь одинаковые имена в разных схемах, что снижает риски утечки данных и иногда повышает производительность. Приложения могут устанавливать путь поиска схемы для текущего выбранного клиента.
+
Такой подход упрощает управление базой данных и масштабирование, поскольку данные каждого арендатора изолированы, что упрощает обслуживание, обновления и резервное копирование. Примерами имен схем могут быть `CUSTOMER_1` и `CUSTOMER_2`.

Объекты базы данных делятся на две категории: не имеющие схемы и имеющие привязку к схеме.

Следующие типы объектов базы данных не имеют схем:

* Пользователи
* Роли
* Отображения пользователей и ролей (`MAPPING`)
* Схемы
* BLOB фильтры
* Табличные пространства

Следующие типы объектов базы данных имеют привязку к схеме:

* Таблицы
* Индексы
* Представления
* Триггеры
* Процедуры
* Функции
* Пакеты
* Домены
* Последовательности (генераторы)
* Исключения
* Наборы символов
* Сортировки

При создании новой базы данных автоматически будут созданы две схемы: `PUBLIC` и `SYSTEM`.

Все системные объекты, привязанные к схеме (например, `RDB$*` и `MON$*`), создаются в выделенной схеме под названием `SYSTEM`. Схема `SYSTEM` имеет разрешение `USAGE` по умолчанию, предоставленное `PUBLIC`, и включена в путь поиска по умолчанию. Это обеспечивает обратную совместимость с предыдущими версиями Firebird.

Хотя схема `SYSTEM` допускает такие операции, как создание индексов и манипуляции этими индексами, в остальном она заблокирована для изменений DDL. Изменение объектов в схеме `SYSTEM` с помощью операций DDL настоятельно не рекомендуется.

Схема с именем `PUBLIC` автоматически создается в новых базах данных с разрешением `USAGE` по умолчанию, предоставленным `PUBLIC`. Однако только владелец базы данных или схемы имеет разрешения по умолчанию для манипулирования объектами в этой схеме.

В отличие от схемы `SYSTEM`, схема `PUBLIC` не является системным объектом и может быть удалена владельцем базы данных или пользователем с разрешением `DROP ANY SCHEMA`. Если восстанавливается резервная копия Firebird 6 или более поздней версии с помощью `gbak`, а схема `PUBLIC` отсутствовала в исходной базе данных, восстановленная база данных также исключит её.

[[fblangref-schema-search-path]]
== Путь поиска

(((SEARCH_PATH)))Сеанс Firebird запускается с начальным путем поиска, списком схем, используемых для разрешения неквалифицированных имен объектов. По умолчанию этот путь установлен на `PUBLIC, SYSTEM`, но его можно настроить с помощью параметра `isc_dpb_search_path` в API.

Начальный путь поиска служит основой для текущего пути поиска, который активно используется во время разрешения объектов. Текущий путь поиска можно динамически обновлять с помощью оператора `SET SEARCH_PATH TO`. При необходимости вы можете сбросить текущий путь поиска до его начальной конфигурации с помощью оператора `ALTER SESSION RESET`.

Несуществующие схемы могут быть включены в путь поиска, но игнорируются во время разрешения имен.

Если `SYSTEM` не включена в список схем, она автоматически добавляется как последняя схема в пути поиска.

Первая существующая схема в пути поиска называется **текущей схемой** и используется исключительно в некоторых операциях.

Привязка неквалифицированных объектов к схеме обычно происходит во **время подготовки оператора**. Исключением является `EXECUTE STATEMENT`, которая подготавливает оператор во **время выполнения**. Другим исключением является функция `MAKE_DBKEY`, когда ее первый аргумент является выражением (а не простым литералом), в этом случае разрешение имени таблицы происходит во **время выполнения**.

Имена объектов могут быть явно квалифицированы с помощью их схемы, например `SCHEMA_NAME.TABLE_NAME`,
`SCHEMA_NAME.TABLE_NAME.COLUMN_NAME` или `SCHEMA_NAME.PACKAGE_NAME.PROCEDURE_NAME`. Однако квалификатор схемы является необязательным. Если он опущен, путь поиска используется для разрешения неквалифицированных имен, а поведение зависит от контекста, в котором появляется имя.

Для операторов `CREATE`, `CREATE OR ALTER` и `RECREATE` система ищет только **текущую схему** (первую допустимую схему в пути поиска) для существующего объекта, и новый объект создается в этой же схеме. Это правило также применяется к операторам `GRANT` и `REVOKE` для операций DDL без подпункта `ON SCHEMA`. Если **текущая схема** недоступна (то есть в пути поиска нет допустимой схемы), возникает ошибка.

Примеры использующие это правило:

[source,sql]
----
create table TABLE1 (ID integer);
recreate table TABLE1 (ID integer);
create or alter function F1 returns integer as begin end;
grant create table to user USER1;
----

Для операторов `ALTER`, `DROP` и других система ищет указанный объект по всем схемам в пути поиска. Ссылка привязана к первому найденному совпадающему объекту. Если ни в одной схеме не существует совпадающего объекта, возникает ошибка.

Примеры использующие это правило:

[source,sql]
----
alter table TABLE1 add X integer;
alter function FUNCTION1 returns integer as begin end;
select * from TABLE1;
----

Поведение путей поиска различается между операторами DML и DDL.

Для операторов DML путь поиска используется для поиска всех указанных неквалифицированных объектов. Например:

[source,sql]
----
insert into TABLE1 values (1);

execute block returns (out DOMAIN1)
as
begin
    select val from TABLE2 into out;
end;
----

В этом случае путь поиска используется для поиска `TABLE1`, `DOMAIN1` и `TABLE2`.

Для операторов DDL путь поиска работает аналогично, но с небольшим отличием. После того, как создаваемый или изменяемый объект привязан к схеме во время подготовки оператора, путь поиска неявно и временно изменяется. Эта корректировка устанавливает путь поиска на схему объекта. Кроме того, схема `SYSTEM` добавляется как последняя схема в путь поиска.

[source,sql]
----
create schema SCHEMA1;
create schema SCHEMA2;

create domain SCHEMA1.DOMAIN1 integer;

-- DOMAIN1 привязан к SCHEMA1 даже без его нахождения в пути поиска, поскольку создаваемая таблица привязана к SCHEMA1
create table SCHEMA1.TABLE1 (id DOMAIN1);

set search_path to SCHEMA2, SCHEMA1;
-- Ошибка: даже если SCHEMA1 находится в пути поиска, TABLE2 привязана к SCHEMA2,
-- поэтому DOMAIN1 ищется только в схеме SCHEMA2
create table TABLE2 (id DOMAIN1);

set search_path to SYSTEM;

create procedure SCHEMA1.PROC1
as
begin
    -- TABLE1 привязана к SCHEMA1 как PROC1
    insert into TABLE1 values (1);
end;
----

См. также <<fblangref-management-set-search-path>>, <<fblangref-management-resetsession>>

[[fblangref-ddl-schema-create]]
== `CREATE SCHEMA`

.Назначение
Создание новой схемы.
(((CREATE SCHEMA)))

.Доступно в
DSQL, ESQL

[[fblangref-ddl-schema-create-syntax]]
.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE SCHEMA [IF NOT EXISTS] <schema name>
    [DEFAULT CHARACTER SET <character set name>]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]

----

.Параметры оператора `CREATE SCHEMA`
[[fblangref-ddl-tbl-create-schema]]
[cols="<1,<3", options="header",stripes="none"]
|===
^|Параметр
^|Описание

|schema name
|Имя схемы базы данных. Может содержать до 63 символов.

|character set name
|Задаёт набор символов по умолчанию для строковых типов данных для объектов внутри схемы.
|===

Оператор `CREATE SCHEMA` создаёт новую схему базы данных.

Если используется предложение `IF NOT SCHEMA`, то оператор `CREATE SCHEMA` попытается создать новую схему без выдачи ошибки, если она уже существует.

(((CREATE SCHEMA, DEFAULT CHARACTER SET)))
Необязательное предложение `DEFAULT CHARACTER SET` задаёт набор символов по умолчанию для строковых типов данных (`CHAR`, `VARCHAR` и `BLOB`) для объектов принадлежащих этой схеме. Если набор символов по умолчанию не указан для схемы, то используется набор символов по умолчанию базы данных.

(((CREATE SCHEMA, DEFAULT SQL SECURITY)))
Необязательное предложение `DEFAULT SQL SECURITY` позволяет задать значение по умолчанию привилегий выполнения для вновь создаваемых объектов схемы. Объекты схемы могут выполняться с привилегиями вызывающего (`INVOKER`) или определяющего пользователя (`DEFINER`). Если предложение `DEFAULT SQL SECURITY` не указано, то схема унаследует привилегии выполнения заданные для базы данных.

В отличие от автоматически созданной схемы `PUBLIC`, вновь созданные схемы предоставляют разрешение `USAGE` только своим владельцам, а не `PUBLIC`.

Имена схем `INFORMATION_SCHEMA` и `DEFINITION_SCHEMA` зарезервированы и не могут использоваться для новых схем.

=== Примеры

.Создание новой схемы с аттрибутами унаследованными от базы данных
[example]
====
[source,sql]
----
CREATE SCHEMA FINANCE;
----
====

.Создание новой схемы с аттрибутами отличными от тех, что указаны при создании БД
[example]
====
[source,sql]
----
CREATE SCHEMA FINANCE
DEFAULT CHARACTER SET UTF8;

CREATE SCHEMA MARKETPLACE
DEFAULT CHARACTER SET UTF8
DEFAULT SQL SECURITY DEFINER;
----
====

.Создание новой схемы, если её не существует
[example]
====
[source,sql]
----
CREATE SCHEMA IF NOT EXISTS FINANCE;
----
====

[[fblangref-ddl-schema-create-who]]
=== Кто может создать схему?

Выполнить оператор `CREATE SCHEMA` могут:

* <<fblangref-security-administrators,Администраторы>>
* Пользователи с привилегией `CREATE SCHEMA`.

Пользователь, создавший схему, становится её владельцем.

.См. также:
<<fblangref-ddl-schema-alter>>,
<<fblangref-ddl-schema-drop>>,
<<fblangref-ddl-schema-create-or-alter>>,
<<fblangref-ddl-schema-recreate>>.

[[fblangref-ddl-schema-alter]]
== `ALTER SCHEMA`

.Назначение
Изменение существующей схемы.
(((ALTER SCHEMA)))

.Доступно в
DSQL, ESQL

[[fblangref-ddl-schema-alter-syntax]]
.Синтаксис
[listing,subs="+quotes,attributes"]
----
ALTER SCHEMA <schema name>
    <alter schema option> [<alter schema option>  ...]

<alter schema option> ::=
    SET DEFAULT CHARACTER SET <character set name> |
    SET DEFAULT SQL SECURITY {DEFINER | INVOKER} |
    DROP DEFAULT CHARACTER SET |
    DROP DEFAULT SQL SECURITY

----

Оператор `ALTER SCHEMA` позволяет изменить аттрибуты по умолчанию для вновь создаваемых объектов схемы.

=== Примеры

.Изменение аттрибутов схемы
[example]
====
[source,sql]
----
ALTER SCHEMA FINANCE
SET DEFAULT CHARACTER SET UTF8;

ALTER SCHEMA MARKETPLACE
SET DEFAULT CHARACTER SET UTF8
DROP DEFAULT SQL SECURITY;
----
====

=== Кто может выполнить ALTER SCHEMA?

Выполнить оператор `ALTER SCHEMA` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец схемы;
* Пользователи с привилегией `ALTER ANY SCHEMA`.

.См. также:
<<fblangref-ddl-schema-create>>,
<<fblangref-ddl-schema-drop>>,
<<fblangref-ddl-schema-create-or-alter>>.

[[fblangref-ddl-schema-create-or-alter]]
== `CREATE OR ALTER SCHEMA`

.Назначение
Создание новой схемы или изменение существующей.
(((CREATE OR ALTER SCHEMA)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs="+quotes,attributes"]
----
CREATE OR ALTER SCHEMA <schema name>
    [DEFAULT CHARACTER SET <character set name>]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]

----

Оператор `CREATE OR ALTER SCHEMA` создаёт схему с указанными аттрибутами, если её не существует, или изменяет аттрибуты схемы на указанные, если схема существует.

=== Примеры

.Создание новой схемы или изменение аттрибутов существующей
[example]
====
[source,sql]
----
CREATE OR ALTER SCHEMA FINANCE
SET DEFAULT CHARACTER SET UTF8;

CREATE OR ALTER SCHEMA MARKETPLACE
DEFAULT CHARACTER SET UTF8
DEFAULT SQL SECURITY INVOKER;
----
====

.См. также:
<<fblangref-ddl-schema-create>>,
<<fblangref-ddl-schema-alter>>,
<<fblangref-ddl-schema-recreate>>.

[[fblangref-ddl-schema-drop]]
== `DROP SCHEMA`

.Назначение
Удаление схемы базы данных.
(((DROP SCHEMA)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs="+quotes,attributes"]
----
DROP SCHEMA [IF EXISTS] <schema name>
----

Оператор `DROP SCHEMA` удаляет существующую схему. Если схема имеет зависимости, то удаление не будет произведено и будет выдана ошибка.

В настоящее время разрешается удалять только пустые схемы, то есть схемы в которых нет ни одного объекта базы данных.

Если используется предложение `IF EXISTS`, то оператор `DROP SCHEMA` попытается удалить схему без выдачи ошибки, если её не существует.

=== Примеры

.Удаление схемы
[example]
====
[source,sql]
----
DROP SCHEMA FINANCE;
----
====

.Удаление схемы, если она существует
[example]
====
[source,sql]
----
DROP SCHEMA IF EXISTS MARKETPLACE;
----
====

=== Кто может удалить схему?

Выполнить оператор `DROP SCHEMA` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец схемы;
* Пользователи с привилегией `DROP ANY SCHEMA`.

.См. также:
<<fblangref-ddl-schema-create>>,
<<fblangref-ddl-schema-alter>>,
<<fblangref-ddl-schema-recreate>>.

[[fblangref-ddl-schema-recreate]]
== `RECREATE SCHEMA`

.Назначение
Создание новой схемы или удаление старой и создание новой схемы.
(((RECREATE SCHEMA)))

.Доступно в
DSQL, ESQL

.Синтаксис
[listing,subs="+quotes,attributes"]
----
RECREATE SCHEMA <schema name>
    [DEFAULT CHARACTER SET <character set name>]
    [DEFAULT SQL SECURITY {DEFINER | INVOKER}]

----

Оператор `CREATE OR ALTER SCHEMA` создаёт схему с указанными аттрибутами, если её не существует, или пересоздаёт схему, если она существует.

=== Примеры

.Пересоздание схемы
[example]
====
[source,sql]
----
RECREATE SCHEMA FINANCE;
----
====

.См. также:
<<fblangref-ddl-schema-create>>,
<<fblangref-ddl-schema-drop>>,
<<fblangref-ddl-schema-create-or-alter>>.
