[[fblangref-ddl-package-body]]
= PACKAGE BODY

[[fblangref-ddl-package-body-create]]
== `CREATE PACKAGE BODY`

.Назначение
Создание тела пакета.
(((CREATE PACKAGE BODY)))

.Доступно в
DSQL

[[fblangref-ddl-pkg-body-create-syntax]]
.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
CREATE PACKAGE BODY [IF NOT EXISTS] [ _pkg-schema_ <period> ] _package_name_
AS
BEGIN
  [<package_item> ...]
  [<package_body_item> ...]
END

<package_item> ::=
    <function declaration>;
  | <aggregate function declaration>;
  | <procedure declaration>;
  | <constant declaration>;
  | <temporary table declaration>;

<function declaration> ::=
  FUNCTION _func_name_ [(<in_params>)]
  RETURNS <type> [NOT NULL] [COLLATE [ _coll-schema_ <period> ] _collation_]
  [DETERMINISTIC]

<aggregate function declaration> ::=
  AGGREGATE FUNCTION _func_name_ [(<in_params>)]
  RETURNS <type> [NOT NULL]
    [COLLATE [ _coll-schema_ <period> ] _collation_]

<procedure declaration> ::=
  PROCEDURE _proc_name_ [(<in_params>)]
  [RETURNS (<out_params>)]

<constant declaration> ::=
  CONSTANT _const_name_ <type> = <constant expression>

<temporary table declaration> ::=
  TEMPORARY TABLE _table_name_
  (
    <column_definition> [, ...]
  )
  [ON COMMIT {DELETE | PRESERVE} ROWS]
  [{[UNIQUE] [ASC | DESC] INDEX _index_name_ (_column_name_)}...]

<package_body_item> ::=
    <function_impl>
  | <agg_function_impl>
  | <procedure_impl>

<function_impl> ::=
  FUNCTION _func_name_ [(<in_impl_params>)]
  RETURNS <type> [NOT NULL] [COLLATE [ _coll-schema_ <period> ] _collation_]
  <routine-body>

<agg_function_impl> ::=
  AGGREGATE FUNCTION _func_name_ [(<in_impl_params>)]
  RETURNS <type> [NOT NULL] [COLLATE [ _coll-schema_ <period> ] _collation_]
  <agg-routine-body>

<procedure_impl> ::=
  PROCEDURE _proc_name_ [(<in_impl_params>)]
  [RETURNS (<out_params>)]
  <routine-body>

<in_params> ::= <inparam> [, <inparam> ...]

<inparam> ::= <param_decl> [{= | DEFAULT} <value>]

<in_impl_params> ::= <param_decl> [, <param_decl> ...]

<value> ::=  {_literal_ | NULL | _context_var_}

<out_params> ::= <outparam> [, <outparam> ...]

<outparam>  ::=  <param_decl>

<param_decl> ::= _paramname_ <type> [NOT NULL] [COLLATE [ _coll-schema_ <period> ] _collation_]

<type> ::=
    <datatype>
  | [TYPE OF] [ _dom-schema_ <period> ] _domain_name_
  | TYPE OF COLUMN [ _rel-schema_ <period> ] _rel_._col_

<datatype> ::=
    <scalar_datatype> | <blob_datatype>

<scalar_datatype> ::=  См. <<fblangref-datatypes-syntax-scalar,Синтаксис скалярных типов данных>>

<blob_datatype> ::= См. <<fblangref-datatypes-syntax-blob,Синтаксис типа данных BLOB>>

<routine-body> ::=
    <psql-routine-body>
  | <external-routine-spec>

<psql-routine-body> ::=
  См. <<fblangref-psql-elements-body-syntax,Синтаксис тела модуля>>

<external-routine-spec> ::=
  <external-routine-reference>
  [AS <extbody>]

<external-routine-reference> ::= EXTERNAL NAME <extname> ENGINE <engine>

<extname> ::= '<module-name>!<routine-name>[!<misc-info>]'
----

[[fblangref-ddl-tbl-createpkgbdy]]
.Параметры оператора `CREATE PACKAGE BODY`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|pkg-schema
|Имя схемы пакета. Если не указано, то заголовок пакета ищется в пути поиска.

|package_name
|Имя пакета. Может содержать до 63 символов.

|function declaration
|Объявление скалярной функции.

|aggregate function declaration
|Объявление агрегатной функции.

|procedure declaration
|Объявление процедуры.

|constant declaration
|Объявление константы.

|temporary table declaration
|Объявление временной таблицы.

|function_impl
|Реализация скалярной функции.

|agg_function_impl
|Реализация агрегатной функции.

|procedure_impl
|Реализация процедуры.

|proc_name
|Имя процедуры.
Может содержать до 63 символов.

|func_name
|Имя функции.
Может содержать до 63 символов.

|const_name
|Имя константы. Может содержать до 63 символов.

|table_name
|Имя временной таблицы. Может содержать до 63 символов.

|index_name
|Имя индекса временной таблицы. Может содержать до 63 символов.

|column_name
|Имя столбца временной таблицы. Может содержать до 63 символов.

|inparam
|Описание входного параметра.

|outparam
|Описание выходного параметра.

|subfunc_impl
|Реализация подпрограммы–функции.

|subproc_impl
|Реализация подпрограммы–процедуры.

|module-name
|Имя внешнего модуля, в котором расположена процедура/функция.

|routine-name
|Внутреннее имя процедуры/функции внутри внешнего модуля.

|misc-info
|Определяемая пользователем информация для передачи в функцию внешнего модуля.

|extbody
|Тело внешней процедуры или функции. Строковый литерал который
может использоваться UDR для различных целей.

|engine
|Имя движка для использования внешних функций.
Обычно указывается имя UDR.

|literal
|Литерал, совместимый по типу с параметром.

|context_var
|Любая контекстная переменная, тип которой совместим с типом параметра.

|paramname
|Имя входного или выходного параметра процедуры/функции.
Может содержать до 63 символов. Имя параметра должно быть уникальным среди входных и выходных параметров процедуры/функции, а также её локальных переменных.

|datatype
|Тип данных SQL.

|coll-schema
|Имя схемы сортировки (сравнения). Если не указано, то сортировка будет найдена в пути поиска.

|collation
|Имя сортировки (сравнения).

|dom-schema
|Имя схемы домена. Если не указано, то домен будет найден в пути поиска.

|domain_name
|Имя домена.

|rel-schema
|Имя схемы таблицы или представления. Если не указано, то таблица или представление будут найдены в пути поиска.

|rel
|Имя таблицы или представления.

|col
|Имя столбца таблицы или представления.

|constant expression
|Выражение для инициализации константы.
|===

Оператор `CREATE PACKAGE BODY` создаёт новое тело пакета. Тело пакета может быть создано только после того как будет создан заголовок пакета. Если заголовка пакета с именем _package_name_ не существует в указанной (текущей) схеме, то будет выдана соответствующая ошибка. Если указано только имя пакета, то его поиск его заголовка происходит в пути поиска.

[IMPORTANT]
====
Поскольку `CREATE PACKAGE BODY` является DDL оператором, то после того как создаваемое тело пакета привязано к схеме во время подготовки оператора, путь поиска неявно и временно изменяется. Эта корректировка устанавливает путь поиска на схему пакета. Кроме того, схема `SYSTEM` добавляется как последняя схема в путь поиска. Это обозначает, что имена объектов метаданных, используемые внутри оператора `CREATE PACKAGE BODY` будут разрешаться относительно этого нового пути поиска.
====

Если используется предложение `IF NOT EXISTS`, то оператор `CREATE PACKAGE BODY` попытается создать новое тело пакета без выдачи ошибки, если оно уже существует. DDL триггеры не будут запускаться, если тело пакета уже существует.

Все процедуры и функции, объявленные в заголовке пакета, должны быть реализованы в теле пакета. Кроме того, должны быть реализованы и все процедуры и функции, объявленные в теле пакета. Процедуры и функции, определенные в теле пакета, но не объявленные в заголовке пакета, не видны вне тела пакета.

Константы и временные таблицы объявленные в заголовке пакета, не могут быть повторно объявлены в теле пакета.

Имена процедур, функций, констант и временных таблиц, объявленные в теле пакета, должны быть уникальны среди имён процедур, функций, констант  временных таблиц, объявленных в заголовке и теле пакета.

.Правила:

* В теле пакеты должны быть реализованы все подпрограммы, с той же сигнатурой, что и объявленные в заголовке и в начале тела пакета.
* Значения по умолчанию для параметров процедур, которые указываются в `<package_item>`, не могут быть переопределены. Это означает, что они могут быть в `<package_body_item>` только для частных процедур, которые не были объявлены.


[NOTE]
====
UDF деклараций (`DECLARE` внешняя функция) не поддерживается внутри пакетов.
====

[[fblangref-ddl-package-body-create-who]]
=== Кто может создать тело пакета?

Выполнить оператор `CREATE PACKAGE BODY` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец пакета;
* Пользователи с привилегией `ALTER ANY PACKAGE`.


[[fblangref-ddl-package-body-create-examples]]
=== Примеры

.Создание тела пакета в текущей схеме
[example]
====
[source,sql]
----

CREATE PACKAGE BODY APP_VAR
AS
BEGIN
  -- приватная константа пакета
  CONSTANT CONTEXT_NAME VARCHAR(63) = 'USER_SESSION';

  -- Возвращает дату начала периода
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    -- Приватная константа CONTEXT_NAME может использоваться
    -- без квалификации внутри собственного пакета
    RETURN RDB$GET_CONTEXT(CONTEXT_NAME, 'DATEBEGIN');
  END

  -- Возвращает дату окончания периода
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    -- Приватная константа CONTEXT_NAME может использоваться
    -- без квалификации внутри собственного пакета
    RETURN RDB$GET_CONTEXT(CONTEXT_NAME, 'DATEEND');
  END

  -- Устанавливает диапазон дат рабочего периода
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    -- Приватная константа CONTEXT_NAME может использоваться
    -- без квалификации внутри собственного пакета
    RDB$SET_CONTEXT(CONTEXT_NAME, 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT(CONTEXT_NAME, 'DATEEND', ADATEEND);
  END
END
----
====

.Создание тела пакета в схеме APP
[example]
====
[source,sql]
----

CREATE PACKAGE BODY APP.APP_VAR
AS
BEGIN
  -- Возвращает дату начала периода
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  -- Возвращает дату окончания периода
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  -- Устанавливает диапазон дат рабочего периода
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----
====

.Создание тела пакета с закрытой временной таблицей
[example]
====
[source,sql]
----
SET TERM !;

CREATE PACKAGE BODY PKG
AS
BEGIN
  -- объявление приватной временной таблицы пакета
  TEMPORARY TABLE T_PRIV(
    ID INTEGER
  )
  ON COMMIT PRESERVE ROWS
  UNIQUE INDEX UQ_T_PRIV_ID (ID);

  PROCEDURE P1(N INTEGER)
  AS
  BEGIN
    -- вставка записи в публичную временную таблицу пакета
    INSERT INTO T_PUB(ID) VALUES (:N);
    -- вставка записи в закрытую временную таблицу пакета
    INSERT INTO T_PRIV(ID) VALUES (:N);
  END

  PROCEDURE P2 RETURNS (N INTEGER)
  AS
  BEGIN
    FOR
      SELECT ID FROM T_PUB INTO :N DO
        SUSPEND;
  END
END!

SET TERM ;!
----
====

.Создание тела пакета с агрегатными функциями
====
[source,sql]
----
-- заголовок создан ранее

SET TERM !;

CREATE PACKAGE BODY PUBLIC.OPTIMIZER_UTILS
AS
BEGIN
  -- временная таблица, которая
  -- используется для сортировки предикатов по селективности.
  TEMPORARY TABLE T_SEL (
    GROUP_ID BINARY(16),
    SELECTIVITY DOUBLE PRECISION
  )
  ON COMMIT DELETE ROWS
  INDEX T_SEL_IDX_GROUP_ID (GROUP_ID);


  /**
   * Расчёт селективности конъюнктов предикатов (предикаты объединённые AND).
   * Предикаты считаются некоррелированными.
   * Общая селективность оценивается как произведения селективностей предикатов.
   *
   * Подход использовался в Firebird 5.0 и более ранних.
   */
  AGGREGATE FUNCTION CONJ_SELECTIVITY_FB50 (A_SELECTIVITY DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION
  AS
    DECLARE S DOUBLE PRECISION;
  BEGIN
    ON START DO
     S = 1;

    ON ACCUMULATE DO
     S = S * A_SELECTIVITY;

    ON GROUP DO
      RETURN S;
  END

  /**
   * Расчёт селективности конъюнктов предикатов (предикаты объединённые AND).
   * Предикаты считаются частично коррелированными.
   * Используется алгоритм Exponential backoff. Суть алгоритма в следующем:
   * Предикаты сортируются по селективности от лучшей к худшей (меньшей к большей),
   * а затем общая селективность рассчитывается по формуле:
   *
   * S = S1 * S2^1/2 * S3^1/4 ... SN^1/2N
   *
   * Подход используется начиная с Firebird 6.0.
   */
  AGGREGATE FUNCTION CONJ_SELECTIVITY_FB60 (A_SELECTIVITY DOUBLE PRECISION)
  RETURNS DOUBLE PRECISION
  AS
    DECLARE GROUP_ID BINARY(16);
    DECLARE S DOUBLE PRECISION;
    DECLARE P DOUBLE PRECISION;
  BEGIN
    ON START DO
    BEGIN
      S = 1;
      P = 1;
      GROUP_ID = GEN_UUID(7);
    END

    ON ACCUMULATE DO
     INSERT INTO T_SEL(GROUP_ID, SELECTIVITY)
     VALUES (:GROUP_ID, :A_SELECTIVITY);

    ON GROUP DO
    BEGIN
      FOR
        SELECT
          SELECTIVITY
        FROM T_SEL
        WHERE GROUP_ID = :GROUP_ID
        ORDER BY SELECTIVITY
        AS CURSOR C
      DO
      BEGIN
        S = S * POWER(C.SELECTIVITY, P);
        P = P * 0.5;
      END

      RETURN S;
    END

    ON FINISH DO
      DELETE FROM T_SEL WHERE GROUP_ID = :GROUP_ID;
  END
END!

SET TERM ;!

WITH
  T (S) AS (
    SELECT 0.25 FROM RDB$DATABASE
    UNION ALL
    SELECT 0.25 FROM RDB$DATABASE
    UNION ALL
    SELECT 0.1 FROM RDB$DATABASE
  )
SELECT
  OPTIMIZER_UTILS.CONJ_SELECTIVITY_FB50(T.S) AS SEL_FB50,
  OPTIMIZER_UTILS.CONJ_SELECTIVITY_FB60(T.S) AS SEL_FB60
FROM T;
----

[listing]
----
               SEL_FB50                SEL_FB60
======================= =======================
   0.006250000000000000     0.03535533905932738
----
====

.См. также:
<<fblangref-ddl-package-body-drop,`DROP PACKAGE BODY`>>, <<fblangref-ddl-package-create,`CREATE PACKAGE`>>.

[[fblangref-ddl-package-body-alter]]
== `ALTER PACKAGE BODY`

.Назначение
Изменение существующего тела пакета.
(((ALTER PACKAGE BODY)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
ALTER PACKAGE BODY [ _pkg-schema_ <period> ] _package_name_
AS
BEGIN
  [<package_item> ...]
  [<package_body_item> ...]
END

Подробнее см. <<fblangref-ddl-pkg-body-create-syntax,CREATE PACKAGE BODY>>.
----

Оператор `ALTER PACKAGE BODY` изменяет существующее тело пакета.

Если указано только имя пакета, то его поиск производится в путях поиска (`SEARCH_PATH`). Будет изменено первое найденное тело пакета с заданным именем среди схем перечисленных в путях поиска.

[[fblangref-ddl-package-body-alter-examples]]
=== Примеры

.Изменение тела пакета
[example]
====
[source,sql]
----
ALTER PACKAGE BODY APP_VAR
AS
BEGIN
  -- Возвращает дату начала периода
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  -- Возвращает дату окончания периода
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  -- Устанавливает диапазон дат рабочего периода
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----
====

.См. также:
<<fblangref-ddl-package-body-create,`CREATE PACKAGE BODY`>>.

[[fblangref-ddl-package-body-createoralter]]
== `CREATE OR ALTER PACKAGE BODY`

.Назначение
Создание нового или изменение существующего тела пакета.
(((CREATE OR ALTER ALTER PACKAGE BODY)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
CREATE OR ALTER PACKAGE BODY [ _pkg-schema_ <period> ] _package_name_
AS
BEGIN
  [<package_item> ...]
  [<package_body_item> ...]
END


Подробнее см. <<fblangref-ddl-pkg-body-create-syntax,CREATE PACKAGE BODY>>.
----

Оператор `CREATE OR ALTER PACKAGE BODY` создаёт новое или изменяет существующее тело пакета. Если тело пакета с заданным именем существовало на момент выполнения оператора, то оно будет изменено, в противном случае создано.

Тело пакета создаётся или изменяется относительно указанной схемы. Если указано только имя пакета, то создание или изменение тела пакета происходит в текущей схеме (первая валидная схема в путях поиска).

[[fblangref-ddl-package-body-createoralter-examples]]
=== Примеры

.Создание нового или изменение существующего тела пакета
[example]
====
[source,sql]
----
CREATE OR ALTER PACKAGE BODY APP_VAR
AS
BEGIN
  -- Возвращает дату начала периода
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  -- Возвращает дату окончания периода
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  -- Устанавливает диапазон дат рабочего периода
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----
====

.См. также:
<<fblangref-ddl-package-body-create,`CREATE PACKAGE BODY`>>,
<<fblangref-ddl-package-body-alter,`ALTER PACKAGE BODY`>>,
<<fblangref-ddl-package-body-recreate,`RECREATE PACKAGE BODY`>>.

[[fblangref-ddl-package-body-drop]]
== `DROP PACKAGE BODY`

.Назначение
Удаление тела пакета.
(((DROP PACKAGE BODY)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes"]
----
DROP PACKAGE BODY [IF EXISTS] [ _pkg-schema_ <period> ] _package_name_
----

.Параметры оператора `DROP PACKAGE BODY`
[cols="<1,<3", options="header",stripes="none"]
|===
^| Параметр
^| Описание

|pkg-schema
|Имя схемы пакета. Если не указано, то пакет будет найден в пути поиска.

|package_name
|Имя пакета.

|===

Оператор `DROP PACKAGE BODY` удаляет тело пакета.

Если указано только имя пакета, то его поиск производится в путях поиска (`SEARCH_PATH`). Будет удалено первое найденной тело пакета с заданным именем среди схем перечисленных в путях поиска.

Если используется предложение `IF EXISTS`, то оператор `DROP PACKAGE BODY` попытается удалить тело пакета без выдачи ошибки, если его не существует. DDL триггеры не будут запускаться, если тело пакета не существует.

[[fblangref-ddl-package-body-drop-who]]
=== Кто может удалить тело пакета?

Выполнить оператор `DROP PACKAGE BODY` могут:

* <<fblangref-security-administrators,Администраторы>>
* Владелец пакета;
* Пользователи с привилегией `ALTER ANY PACKAGE`.


[[fblangref-ddl-package-body-drop-examples]]
=== Примеры

.Удаление тела пакета
[example]
====
[source,sql]
----
DROP PACKAGE BODY APP_VAR;
----
====

.Удаление тела пакета, если оно существует
[example]
====
[source,sql]
----
DROP PACKAGE BODY IF EXISTS APP_VAR;
----
====

.См. также:
<<fblangref-ddl-package-body-create,`CREATE PACKAGE BODY`>>, <<fblangref-ddl-package-drop,`DROP PACKAGE`>>.

[[fblangref-ddl-package-body-recreate]]
== `RECREATE PACKAGE BODY`

.Назначение
Создание нового и пересоздание существующего тела пакета.
(((RECREATE PACKAGE BODY)))

.Доступно в
DSQL

.Синтаксис
[listing,subs="+quotes,macros,attributes"]
----
RECREATE PACKAGE BODY [ _pkg-schema_ <period> ] _package_name_
AS
BEGIN
  [<package_item> ...]
  [<package_body_item> ...]
END

Подробнее см. <<fblangref-ddl-pkg-body-create-syntax,CREATE PACKAGE BODY>>.
----

Оператор `RECREATE PACKAGE BODY` создаёт новое или пересоздаёт существующее тело пакета. Если тело пакета с таким именем уже существует в указанной (текущей) схеме, то оператор попытается удалить его и создать новое тело пакета. Если указано только имя пакета, то его поиск происходит в текущей схеме. После пересоздания тела пакета привилегии на выполнение подпрограмм пакета и привилегии самого пакета сохраняются.

Пакет создаётся или пересоздаётся относительно указанной схемы. Если указано только имя пакета, то создание или пересоздание его тела происходит в текущей схеме (первая валидная схема в путях поиска).

[[fblangref-ddl-package-body-recreate-examples]]
=== Примеры

.Пересоздание тела пакета
[example]
====
[source,sql]
----
RECREATE PACKAGE BODY APP_VAR
AS
BEGIN
  -- Возвращает дату начала периода
  FUNCTION GET_DATEBEGIN() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEBEGIN');
  END
  -- Возвращает дату окончания периода
  FUNCTION GET_DATEEND() RETURNS DATE DETERMINISTIC
  AS
  BEGIN
    RETURN RDB$GET_CONTEXT('USER_SESSION', 'DATEEND');
  END
  -- Устанавливает диапазон дат рабочего периода
  PROCEDURE SET_DATERANGE(ADATEBEGIN DATE, ADATEEND DATE)
  AS
  BEGIN
    RDB$SET_CONTEXT('USER_SESSION', 'DATEBEGIN', ADATEBEGIN);
    RDB$SET_CONTEXT('USER_SESSION', 'DATEEND', ADATEEND);
  END
END
----
====

.См. также:
<<fblangref-ddl-package-body-create,`CREATE PACKAGE BODY`>>,
<<fblangref-ddl-package-body-drop,`DROP PACKAGE BODY`>>.
